package main

import (
	"encoding/json/v2"
	"testing"
)

// TestPresetConfigsLoadIntoAppConfig verifies that every preset config
// generated by `cqrs-lint init` can be unmarshaled into AppConfig without
// a type-mismatch error. This is a regression test for the SHOWSTOPPER bug
// where the default preset generated `"exclude": []` (JSON array) but the
// Exclude field is a string, causing every new user's config to fail loading.
func TestPresetConfigsLoadIntoAppConfig(t *testing.T) {
	t.Parallel()

	for name, content := range presetConfigs {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			var cfg AppConfig
			// cmdguard uses MatchCaseInsensitiveNames(true) when loading
			// config files (koanf_loader.go:146). Mirror that here.
			err := json.Unmarshal([]byte(content), &cfg,
				json.MatchCaseInsensitiveNames(true))
			if err != nil {
				t.Fatalf("preset %q config does not load into AppConfig: %v\nconfig:\n%s",
					name, err, content)
			}
		})
	}
}
