package main

import (
	"path"
	"sort"
	"strconv"
	"strings"

	"github.com/larsartmann/go-cqrs-lite/cmd/cqrs-lint/v4/pkg/rules"
)

func categoryTitle(c string) string {
	titles := map[string]string{
		"correctness": "Correctness", "api": "API", "boilerplate": "Boilerplate",
		"performance": "Performance", "consistency": "Consistency",
		"architecture": "Architecture", "security": "Security",
		"testing": "Testing", "version": "Version", "adoption": "Adoption",
	}
	if t, ok := titles[c]; ok {
		return t
	}
	return strings.ToUpper(c[:1]) + c[1:]
}

// markdownCategoryOrder fixes the RULES.md section order; unknown categories
// are appended after these so a new category never breaks generation.
var markdownCategoryOrder = []string{
	"correctness", "api", "boilerplate", "performance", "consistency",
	"architecture", "security", "testing", "version", "adoption",
}

// v007AdrLinks are rendered inside the V007 section: the rule spans three
// v5-removal ADRs, and its catalog DocURL anchors here.
func v007AdrLinks() []string {
	return []string{
		"docs/adr/0114-tombstone-as-domain-event.md",
		"docs/adr/0123-v5-unification-single-composition-root.md",
		"docs/adr/0126-metadata-generic-store-transforms-wal-unification.md",
	}
}

// renderRulesMarkdown emits the full anchored RULES.md page: one
// <a id="<lowercase-id>"></a> anchor per catalog entry so rule DocURLs
// (RULES.md#c001 ...) resolve on GitHub.
func renderRulesMarkdown() string {
	categoryOrder := []string{
		"correctness", "api", "boilerplate", "performance", "consistency",
		"architecture", "security", "testing", "version", "adoption",
	}

	all := rules.AllRules()
	byCat := make(map[string][]rules.RuleInfo, len(all))
	for _, r := range all {
		byCat[r.Category] = append(byCat[r.Category], r)
	}

	cats := make([]string, 0, len(byCat))
	for _, c := range categoryOrder {
		if len(byCat[c]) > 0 {
			cats = append(cats, c)
		}
	}
	seen := make(map[string]bool, len(cats))
	for _, c := range cats {
		seen[c] = true
	}
	extra := make([]string, 0)
	for c := range byCat {
		if !seen[c] {
			extra = append(extra, c)
		}
	}
	sort.Strings(extra)
	cats = append(cats, extra...)

	var b strings.Builder
	b.WriteString("# cqrs-lint Rule Catalog\n\n")
	b.WriteString("<!-- Generated by `cqrs-lint rules --markdown`. DO NOT EDIT BY HAND. -->\n")
	b.WriteString("<!-- Regenerate: cd cmd/cqrs-lint && GOWORK=off go run . rules --markdown > RULES.md -->\n\n")
	b.WriteString("Detectors per category (severities: `error` blocks CI, `warning` reports, `info` is advisory):\n\n")
	b.WriteString("| Category | Rules | Section |\n|---|---|---|\n")
	for _, c := range cats {
		b.WriteString("| [" + categoryTitle(c) + "](#" + c + ") | " + strconv.Itoa(len(byCat[c])) + " | " + categoryIDRange(byCat[c]) + " |\n")
	}

	for _, c := range cats {
		b.WriteString("\n## " + categoryTitle(c) + "\n\n")
		rs := byCat[c]
		sort.Slice(rs, func(i, j int) bool { return rs[i].ID < rs[j].ID })
		for _, r := range rs {
			b.WriteString("<a id=\"" + strings.ToLower(r.ID) + "\"></a>\n\n")
			b.WriteString("#### " + r.ID + " — `" + r.Name + "`\n\n")
			b.WriteString("Severity: `" + r.Severity + "` · Confidence: `" + r.Confidence + "` · Auto-fix: " + yesNo(r.AutoFix) + " · Category: `" + r.Category + "`\n\n")
			b.WriteString(r.Description + "\n")
			if links := ruleDocLinks(r); len(links) > 0 {
				b.WriteString("\nReferences:\n\n")
				for _, l := range links {
					b.WriteString("- " + l + "\n")
				}
			}
			b.WriteString("\n")
		}
	}

	return b.String()
}

// ruleDocLinks returns extra reference links for rules whose documentation
// spans multiple sources (V007 removals live in three ADRs).
func ruleDocLinks(r rules.RuleInfo) []string {
	if r.ID != "V007" {
		return nil
	}
	links := make([]string, 0, 3)
	for _, adr := range v007AdrLinks() {
		base := strings.TrimSuffix(path.Base(adr), ".md")
		num, _, _ := strings.Cut(base, "-")
		links = append(links, "[ADR "+num+"](../../"+adr+")")
	}
	return links
}

// categoryIDRange summarizes a category's ID span, e.g. "C001–C042".
func categoryIDRange(rs []rules.RuleInfo) string {
	if len(rs) == 0 {
		return "—"
	}
	lo, hi := rs[0].ID, rs[0].ID
	for _, r := range rs {
		if r.ID < lo {
			lo = r.ID
		}
		if r.ID > hi {
			hi = r.ID
		}
	}
	if lo == hi {
		return lo
	}
	return lo + "–" + hi
}

func yesNo(v bool) string {
	if v {
		return "yes"
	}
	return "no"
}
