version: "2"
run:
  timeout: 5m
  go: ""
  build-tags: []
  allow-parallel-runners: false
  allow-serial-runners: false
  issues-exit-code: 1
  tests: true
output:
  formats: {}
linters:
  enable:
    - unparam
    - errchkjson
    - gocyclo
    - gosmopolitan
    - misspell
    - zerologlint
    - nolintlint
    - govet
    - dupl
    - intrange
    - musttag
    - protogetter
    - bodyclose
    - gocritic
    - nilerr
    - nilnil
    - spancheck
    - copyloopvar
    - exhaustruct
    - funlen
    - gochecknoinits
    - prealloc
    - unconvert
    - errcheck
    - forcetypeassert
    - loggercheck
    - nilnesserr
    - perfsprint
    - revive
    - unused
    - cyclop
    - nestif
    - recvcheck
    - sqlclosecheck
    - staticcheck
    - thelper
    - paralleltest
    - testifylint
    - gocognit
    - nakedret
    - sloglint
    - maintidx
    - errorlint
    - exhaustive
    - gochecknoglobals
    - gochecksumtype
    - goconst
    - gosec
    - reassign
    - usetesting
    - noctx
    - predeclared
    - wrapcheck
    - durationcheck
    - errname
    - interfacebloat
    - rowserrcheck
    - contextcheck
    - ginkgolinter
    - mirror
    - wastedassign
    - ineffassign
formatters:
  enable:
    - golines
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
