package rules

func consistencyRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "D001",
			Name:        "inconsistent-event-naming",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Mixed dot notation and PascalCase event types",
			AutoFix:     false,
		},
		{
			ID:          "D002",
			Name:        "inconsistent-json-casing",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "low",
			Description: "Mixed camelCase and snake_case JSON tags",
			AutoFix:     false,
		},
		{
			ID:          "D003",
			Name:        "inconsistent-logging-library",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "high",
			Description: "Project mixes multiple logging libraries",
			AutoFix:     false,
		},
		{
			ID:          "D005",
			Name:        "stale-documentation-version",
			Category:    "consistency",
			Severity:    "warning",
			Confidence:  "low",
			Description: "Documentation references different version than go.mod",
			AutoFix:     false,
		},
		{
			ID:          "D006",
			Name:        "missing-errorfamily",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "medium",
			Description: "errors.New or fmt.Errorf without %w bypasses the 6-family error taxonomy",
			AutoFix:     false,
		},
		{
			ID:          "D007",
			Name:        "inconsistent-event-creation-api",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Project uses both event.New and event.NewEvent — standardize on event.New",
			AutoFix:     true,
		},
		{
			ID:          "D008",
			Name:        "inconsistent-codec-usage",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Project mixes event.DecodePayload (explicit codec) and event.DecodePayloadAuto",
			AutoFix:     false,
		},
		{
			ID:          "D009",
			Name:        "inconsistent-close-pattern",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "low",
			Description: "Project uses both io.Closer and anonymous interface{ Close() error }",
			AutoFix:     false,
		},
		{
			ID:          "D010",
			Name:        "generic-error-code-internal",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Generic \"internal\" error code in errorfamily.Wrap* — use descriptive namespaced codes",
			AutoFix:     false,
		},
		{
			ID:          "D011",
			Name:        "nil-payload-event",
			Category:    "consistency",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Event created with nil payload — cannot be decoded, provides no audit trail",
			AutoFix:     false,
		},
		{
			ID:          "D012",
			Name:        "raw-print-in-handler",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "low",
			Description: "Raw fmt/log print in CQRS handler — use structured logging (slog)",
			AutoFix:     false,
		},
		{
			ID:          "D013",
			Name:        "missing-schema-version",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "low",
			Description: "Events created without event.WithSchemaVersion — schema evolution (upcasting) is impossible to add retroactively",
			AutoFix:     false,
		},
		{
			ID:          "D014",
			Name:        "event-payload-without-json-tags",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Event payload struct without json tags — Go field names used in JSON encoding",
			AutoFix:     false,
		},
		{
			ID:          "D015",
			Name:        "nullable-payload-fields",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Nullable pointer fields in event payloads — nil-dereference panic risk on decode",
			AutoFix:     false,
		},
		{
			ID:          "D016",
			Name:        "payload-too-many-fields",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "high",
			Description: "Event payload struct with >20 fields — hard to evolve and serialize",
			AutoFix:     false,
		},
		{
			ID:          "D017",
			Name:        "raw-errors-in-domain",
			Category:    "consistency",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Unclassified errors.New/fmt.Errorf in domain decider files — business rule violations must use errorfamily taxonomy",
			AutoFix:     false,
		},
		{
			ID:          "D018",
			Name:        "stale-catalog-entries",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "low",
			Description: "Catalog entry references event type not present in any event.NewEvent call — may be stale",
			AutoFix:     false,
		},
		{
			ID:          "D019",
			Name:        "stale-spec-freshness",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "low",
			Description: "Exported specs are stale: event types exist that are not in the catalog",
			AutoFix:     false,
		},
	}
}
