package rules

func architectureRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "E001",
			Name:        "layer-violation",
			Category:    "architecture",
			Severity:    "error",
			Confidence:  "high",
			Description: "Tier-0 module imports Tier-3+ module",
			AutoFix:     false,
		},
		{
			ID:          "E002",
			Name:        "circular-dependency",
			Category:    "architecture",
			Severity:    "error",
			Confidence:  "high",
			Description: "Two modules import each other",
			AutoFix:     false,
		},
		{
			ID:          "E003",
			Name:        "missing-module-boundary",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "low",
			Description: "All CQRS code in one package without boundaries",
			AutoFix:     false,
		},
		{
			ID:          "E004",
			Name:        "event-not-in-catalog",
			Category:    "architecture",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Event type emitted but not in catalog",
			AutoFix:     false,
		},
		{
			ID:          "E005",
			Name:        "command-without-handler",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Command type defined but never registered",
			AutoFix:     false,
		},
		{
			ID:          "E006",
			Name:        "event-without-projection",
			Category:    "architecture",
			Severity:    "info",
			Confidence:  "low",
			Description: "Event type emitted but no projection handles it",
			AutoFix:     false,
		},
		{
			ID:          "E007",
			Name:        "query-without-handler",
			Category:    "architecture",
			Severity:    "info",
			Confidence:  "low",
			Description: "Query type defined but never registered",
			AutoFix:     false,
		},
		{
			ID:          "E008",
			Name:        "stack-preset-bypass",
			Category:    "architecture",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Stack presets available but decider.NewRepository called directly",
			AutoFix:     false,
		},
		{
			ID:          "E009",
			Name:        "no-http-integration",
			Category:    "architecture",
			Severity:    "info",
			Confidence:  "low",
			Description: "Command and query dispatchers present but no delivery layer — watermill bridge, go-sse, or cqrs-htmx (ADR-0127)",
			AutoFix:     false,
		},
		{
			ID:          "E010",
			Name:        "capture-without-validation",
			Category:    "architecture",
			Severity:    "info",
			Confidence:  "low",
			Description: "Events written to store without decider domain validation",
			AutoFix:     false,
		},
		{
			ID:          "E011",
			Name:        "excessive-adapter-layers",
			Category:    "architecture",
			Severity:    "info",
			Confidence:  "low",
			Description: "3+ Adapter types between command handlers and decider",
			AutoFix:     false,
		},
		{
			ID:          "E012",
			Name:        "dual-write-no-completion",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "low",
			Description: "Dual-write bus without feature flag or completion check",
			AutoFix:     false,
		},
		{
			ID:          "E013",
			Name:        "signing-disabled-by-default",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Signing/encryption imported but config Enabled: false",
			AutoFix:     false,
		},
		{
			ID:          "E014",
			Name:        "no-read-your-writes",
			Category:    "architecture",
			Severity:    "info",
			Confidence:  "low",
			Description: "Projectionhost used without drain/wait for read consistency",
			AutoFix:     false,
		},
		{
			ID:          "E015",
			Name:        "watermill-no-ordered-delivery",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "high",
			Description: "BlockPublishUntilSubscriberAck: false breaks ordered delivery",
			AutoFix:     false,
		},
		{
			ID:          "E016",
			Name:        "missing-health-checks",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Server-mode project without HealthCheck — Kubernetes probes need it",
			AutoFix:     false,
			DocURL:      "https://github.com/larsartmann/go-cqrs-lite/blob/main/cmd/cqrs-lint/RULES.md#e016",
		},
		{
			ID:          "E017",
			Name:        "missing-graceful-shutdown",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "signal.Notify without GracefulClose/Stop — in-flight events lost on SIGTERM",
			AutoFix:     false,
			DocURL:      "https://github.com/larsartmann/go-cqrs-lite/blob/main/cmd/cqrs-lint/RULES.md#e017",
		},
	}
}

