package rules

func correctnessRulesPart2() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "C022",
			Name:        "context-discarded",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "_ = ctx explicitly discards context — breaks cancellation, timeouts, tracing",
			AutoFix:     false,
		},
		{
			ID:          "C023",
			Name:        "shutdown-error-ignored",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Stop/Close/Shutdown error ignored — pending events or resources may be lost",
			AutoFix:     false,
		},
		{
			ID:          "C024",
			Name:        "dual-write-without-rollback",
			Category:    "correctness",
			Severity:    "error",
			Confidence:  "medium",
			Description: "In-memory mutation + DB write without transaction — state diverges on failure",
			AutoFix:     false,
		},
		{
			ID:          "C025",
			Name:        "bare-errorf-in-cqrs",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "fmt.Errorf without %w in CQRS code — loses error classification",
			AutoFix:     false,
		},
		{
			ID:          "C026",
			Name:        "idempotency-ttl-mismatch",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Literal TTL passed but a TTL constant is defined and not used — dead/misleading code",
			AutoFix:     false,
		},
		{
			ID:          "C027",
			Name:        "bus-subscription-alongside-projectionhost",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "bus.Subscribe alongside projectionhost — events may be processed twice",
			AutoFix:     false,
		},
		{
			ID:          "C028",
			Name:        "swallowed-cqrs-error",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Error from Dispatch/Execute/Load/Register discarded — CQRS operation failures indicate real problems",
			AutoFix:     false,
		},
		{
			ID:          "C029",
			Name:        "queryidempotency-nil-keyextractor",
			Category:    "correctness",
			Severity:    "error",
			Confidence:  "high",
			Description: "QueryIdempotency with nil keyExtractor panics at runtime — queries have no default identity",
			AutoFix:     false,
		},
		{
			ID:          "C030",
			Name:        "no-ctx-cancel-in-loop",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Infinite loop without context cancellation — goroutine leaks on shutdown",
			AutoFix:     false,
		},
		{
			ID:          "C031",
			Name:        "error-swallow-in-handler",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Handler checks error but returns nil — command/query appears successful when it failed",
			AutoFix:     false,
		},
		{
			ID:          "C032",
			Name:        "ctx-propagation-gap",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "context.Background()/TODO() inside handler that receives ctx — breaks tracing and cancellation",
			AutoFix:     false,
		},
		{
			ID:          "C033",
			Name:        "missing-error-wrapping",
			Category:    "correctness",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Bare return err from CQRS call — wrap with context for debuggability",
			AutoFix:     false,
		},
		{
			ID:          "C034",
			Name:        "goroutine-without-ctx",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "go func() without ctx — goroutine outlives parent handler, resource leak on shutdown",
			AutoFix:     false,
		},
		{
			ID:          "C035",
			Name:        "unprotected-map-field",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Map field without sync.Mutex/sync.RWMutex in read model/handler — data race risk in concurrent handlers",
			AutoFix:     false,
		},
		{
			ID:          "C036",
			Name:        "store-backend-mismatch",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Checkpoint/snapshot/idempotency store backend differs from event store — crash-recovery guarantees break",
			AutoFix:     false,
		},
		{
			ID:          "C037",
			Name:        "typed-store-codec-mismatch",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Typed store (snapshot, command, query, or kv) codec differs from repository codec — store cannot be decoded, loads as corrupt/zero state",
			AutoFix:     false,
		},
		{
			ID:          "C038",
			Name:        "event-type-typo",
			Category:    "correctness",
			Severity:    "error",
			Confidence:  "high",
			Description: "Emitted event type string is a likely typo of a fold case label — event silently dropped during replay",
			AutoFix:     false,
		},
		{
			ID:          "C039",
			Name:        "goroutine-leak-in-handler",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Unmanaged goroutine inside event/command handler — resource leak and ordering violation",
			AutoFix:     false,
		},
		{
			ID:          "C040",
			Name:        "dead-fold-case",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Fold switch case handles an event type that is never emitted via event.New — dead code or a typo in the fold case string",
			AutoFix:     false,
		},
		{
			ID:          "C041",
			Name:        "save-ignores-expected-version",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Custom Save method does not reference expectedVersion — optimistic concurrency control not enforced",
			AutoFix:     false,
		},
		{
			ID:          "C042",
			Name:        "save-with-zero-version",
			Category:    "correctness",
			Severity:    "info",
			Confidence:  "low",
			Description: "Save called with expectedVersion=0 — optimistic concurrency bypassed for this write",
			AutoFix:     false,
		},
	}
}
