package rules

func performanceRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "P001",
			Name:        "load-in-subscribeall",
			Category:    "performance",
			Severity:    "error",
			Confidence:  "high",
			Description: "repo.Load inside SubscribeAll handler — O(N²) replay",
			AutoFix:     false,
		},
		{
			ID:          "P006",
			Name:        "polling-loop-short-interval",
			Category:    "performance",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "time.Sleep <100ms inside a for-loop — busy-poll pattern, use channel/callback/sync.Cond",
			AutoFix:     false,
		},
		{
			ID:          "P007",
			Name:        "manual-retry-bitshift",
			Category:    "performance",
			Severity:    "error",
			Confidence:  "high",
			Description: "Manual retry loop with bitshift backoff — corrupts time.Duration, use retry.Do",
			AutoFix:     false,
		},
		{
			ID:          "P008",
			Name:        "projectionhost-no-batchsize",
			Category:    "performance",
			Severity:    "info",
			Confidence:  "medium",
			Description: "projectionhost.New without WithBatchSize — default batch size may bottleneck throughput",
			AutoFix:     false,
		},
		{
			ID:          "P009",
			Name:        "json-codec-large-payloads",
			Category:    "performance",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Large event payload using JSON codec — CBOR is ~35% smaller",
			AutoFix:     false,
		},
		{
			ID:          "P010",
			Name:        "no-snapshot-large-aggregate",
			Category:    "performance",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Aggregate with collection-type state without snapshot strategy or cache — expensive reloads",
			AutoFix:     false,
		},
		{
			ID:          "P011",
			Name:        "unbounded-memory-growth",
			Category:    "performance",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Read model with map field without size limit — grows unboundedly, risk of OOM",
			AutoFix:     false,
		},
		{
			ID:          "P012",
			Name:        "missing-sqlite-wal",
			Category:    "performance",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "SQLite store without WAL mode — prone to 'database is locked' errors under concurrent access",
			AutoFix:     false,
			DocURL:      "https://github.com/larsartmann/go-cqrs-lite/blob/main/cmd/cqrs-lint/RULES.md#p012",
		},
		{
			ID:          "P013",
			Name:        "missing-sqlite-busy-timeout",
			Category:    "performance",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "SQLite store without busy_timeout — 'database is locked' errors under concurrent access",
			AutoFix:     false,
		},
	}
}

