package rules

func boilerplateRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "B001",
			Name:        "single-event-helper",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Single-event helper function — use event.Single()",
			AutoFix:     false,
		},
		{
			ID:          "B002",
			Name:        "manual-repository-wiring",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Manual store+bus+repository wiring — use stack preset",
			AutoFix:     false,
		},
		{
			ID:          "B003",
			Name:        "subscribeall-large-switch",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "medium",
			Description: "SubscribeAll with >5 switch cases — split into projections",
			AutoFix:     false,
		},
		{
			ID:          "B004",
			Name:        "command-constructor-boilerplate",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Command with many fields — use cqrs-gen",
			AutoFix:     false,
		},
		{
			ID:          "B005",
			Name:        "fold-switch-boilerplate",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Fold uses switch — consider decider.StrictApply",
			AutoFix:     false,
		},
		{
			ID:          "B006",
			Name:        "duplicate-fk-stub-sql",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Duplicated foreign-key SQL — centralize as shared constant",
			AutoFix:     false,
		},
		{
			ID:          "B007",
			Name:        "repeated-handler-registration",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "3+ consecutive handler registrations — use table-driven approach",
			AutoFix:     false,
		},
		{
			ID:          "B008",
			Name:        "manual-retry-implementation",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Manual retry loop — use retry.Do",
			AutoFix:     false,
		},
		{
			ID:          "B009",
			Name:        "emit-function-boilerplate",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Hand-written emit/publish helper wrapping event.New + bus.Publish",
			AutoFix:     false,
		},
		{
			ID:          "B010",
			Name:        "catalog-event-list-boilerplate",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "3+ catalog.Event calls — use cqrs-gen to auto-generate",
			AutoFix:     false,
		},
		{
			ID:          "B011",
			Name:        "must-marshal-helper",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "mustMarshal helper — use event.New",
			AutoFix:     false,
		},
		{
			ID:          "B012",
			Name:        "make-event-helper",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Hand-written makeEvent/newEvent helper — use event.New",
			AutoFix:     false,
		},
		{
			ID:          "B013",
			Name:        "missing-correlation-enricher",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Repository without correlation enricher",
			AutoFix:     false,
		},
		{
			ID:          "B014",
			Name:        "missing-otel-middleware",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "low",
			Description: "Bus/dispatcher lacks OTel tracing middleware",
			AutoFix:     false,
		},
		{
			ID:          "B015",
			Name:        "missing-test-utilities",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "low",
			Description: "Project has tests but no testutil/eventtest imports",
			AutoFix:     false,
		},
		{
			ID:          "B016",
			Name:        "manual-checkpoint-replay",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Manual checkpoint table + journal replay loop — use projectionhost.Host",
			AutoFix:     false,
		},
		{
			ID:          "B017",
			Name:        "manual-readmodel-rebuild",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Read model rebuilt from scratch on startup — use incremental catch-up with checkpoints",
			AutoFix:     false,
		},
		{
			ID:          "B018",
			Name:        "repeated-subscribe-boilerplate",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "medium",
			Description: "3+ bus.Subscribe calls in same file — extract into table-driven registration",
			AutoFix:     false,
		},
		{
			ID:          "B019",
			Name:        "load-in-subscribeall",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "high",
			Description: "repo.Load inside SubscribeAll handler — O(N^2) replay",
			AutoFix:     false,
		},
		{
			ID:          "B020",
			Name:        "manual-legacy-upcasting",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Manual field upcasting in decode function — use schema.NewUpcaster",
			AutoFix:     false,
		},
		{
			ID:          "B021",
			Name:        "fold-without-strictapply",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Fold function silently ignores unknown events — use decider.StrictApply",
			AutoFix:     false,
		},
		{
			ID:          "B022",
			Name:        "manual-correlation-enricher",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Custom enricher instead of decider.CommandCausalityEnricher",
			AutoFix:     false,
		},
		{
			ID:          "B023",
			Name:        "missing-command-middleware",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Command dispatcher has no middleware — panics in handlers crash the process",
			AutoFix:     false,
		},
		{
			ID:          "B024",
			Name:        "missing-bus-recovery",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Event bus has no recovery middleware — panics in handlers crash the bus",
			AutoFix:     false,
		},
		{
			ID:          "B025",
			Name:        "missing-state-cache",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "low",
			Description: "Repository without WithStateCache — hot streams benefit from incremental loads",
			AutoFix:     false,
		},
		{
			ID:          "B026",
			Name:        "missing-catalog-registration",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "medium",
			Description: "3+ event types but no catalog import — documentation generation unavailable",
			AutoFix:     false,
		},
		{
			ID:          "B027",
			Name:        "hardcoded-stream-type",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "low",
			Description: "Hardcoded stream-type string literal — use a constant for consistency",
			AutoFix:     false,
		},
		{
			ID:          "B028",
			Name:        "manual-goroutine-dispatch",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "low",
			Description: "Manual goroutine dispatch of command — deriver.AsHandler provides idempotent dispatch",
			AutoFix:     false,
		},
	}
}

func performanceRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "P001",
			Name:        "load-in-subscribeall",
			Category:    "performance",
			Severity:    "error",
			Confidence:  "high",
			Description: "repo.Load inside SubscribeAll handler — O(N²) replay",
			AutoFix:     false,
		},
		{
			ID:          "P006",
			Name:        "polling-loop-short-interval",
			Category:    "performance",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "time.Sleep <100ms inside a for-loop — busy-poll pattern, use channel/callback/sync.Cond",
			AutoFix:     false,
		},
		{
			ID:          "P007",
			Name:        "manual-retry-bitshift",
			Category:    "performance",
			Severity:    "error",
			Confidence:  "high",
			Description: "Manual retry loop with bitshift backoff — corrupts time.Duration, use retry.Do",
			AutoFix:     false,
		},
		{
			ID:          "P008",
			Name:        "projectionhost-no-batchsize",
			Category:    "performance",
			Severity:    "info",
			Confidence:  "medium",
			Description: "projectionhost.New without WithBatchSize — default batch size may bottleneck throughput",
			AutoFix:     false,
		},
		{
			ID:          "P009",
			Name:        "json-codec-large-payloads",
			Category:    "performance",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Large event payload using JSON codec — CBOR is ~35% smaller",
			AutoFix:     false,
		},
		{
			ID:          "P010",
			Name:        "no-snapshot-large-aggregate",
			Category:    "performance",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Aggregate with collection-type state without snapshot strategy or cache — expensive reloads",
			AutoFix:     false,
		},
		{
			ID:          "P011",
			Name:        "unbounded-memory-growth",
			Category:    "performance",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Read model with map field without size limit — grows unboundedly, risk of OOM",
			AutoFix:     false,
		},
		{
			ID:          "P012",
			Name:        "missing-sqlite-wal",
			Category:    "performance",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "SQLite store without WAL mode — prone to 'database is locked' errors under concurrent access",
			AutoFix:     false,
		},
	}
}

func versionRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "V001",
			Name:        "mixed-major-versions",
			Category:    "version",
			Severity:    "error",
			Confidence:  "high",
			Description: "Project mixes v3 and v4 go-cqrs-lite modules — APIs are incompatible",
			AutoFix:     false,
		},
		{
			ID:          "V002",
			Name:        "unpinned-version",
			Category:    "version",
			Severity:    "warning",
			Confidence:  "high",
			Description: "go-cqrs-lite dependency pinned to a pseudo-version instead of a tagged release",
			AutoFix:     false,
		},
		{
			ID:          "V003",
			Name:        "version-lag",
			Category:    "version",
			Severity:    "info",
			Confidence:  "high",
			Description: "go-cqrs-lite version more than 2 minor versions behind latest known release",
			AutoFix:     false,
		},
		{
			ID:          "V004",
			Name:        "vendored-third-party",
			Category:    "version",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Vendored go-cqrs-lite code in third_party/ — bypasses go.mod updates",
			AutoFix:     false,
		},
		{
			ID:          "V005",
			Name:        "eventtest-vendored-mismatch",
			Category:    "version",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Vendored eventtest alongside go-cqrs-lite imports — version mismatch workaround",
			AutoFix:     false,
		},
		{
			ID:          "V006",
			Name:        "mixed-version-pins",
			Category:    "version",
			Severity:    "warning",
			Confidence:  "high",
			Description: "go-cqrs-lite modules within the same major version pinned to different releases",
			AutoFix:     false,
		},
	}
}

func consistencyRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "D001",
			Name:        "inconsistent-event-naming",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Mixed dot notation and PascalCase event types",
			AutoFix:     false,
		},
		{
			ID:          "D002",
			Name:        "inconsistent-json-casing",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "low",
			Description: "Mixed camelCase and snake_case JSON tags",
			AutoFix:     false,
		},
		{
			ID:          "D003",
			Name:        "inconsistent-logging-library",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "high",
			Description: "Project mixes multiple logging libraries",
			AutoFix:     false,
		},
		{
			ID:          "D005",
			Name:        "stale-documentation-version",
			Category:    "consistency",
			Severity:    "warning",
			Confidence:  "low",
			Description: "Documentation references different version than go.mod",
			AutoFix:     false,
		},
		{
			ID:          "D006",
			Name:        "missing-errorfamily",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "medium",
			Description: "errors.New or fmt.Errorf without %w bypasses the 6-family error taxonomy",
			AutoFix:     false,
		},
		{
			ID:          "D007",
			Name:        "inconsistent-event-creation-api",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Project uses both event.New and event.NewEvent — standardize on event.New",
			AutoFix:     false,
		},
		{
			ID:          "D008",
			Name:        "inconsistent-codec-usage",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Project mixes event.DecodePayload (explicit codec) and event.DecodePayloadAuto",
			AutoFix:     false,
		},
		{
			ID:          "D009",
			Name:        "inconsistent-close-pattern",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "low",
			Description: "Project uses both io.Closer and anonymous interface{ Close() error }",
			AutoFix:     false,
		},
		{
			ID:          "D010",
			Name:        "generic-error-code-internal",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Generic \"internal\" error code in errorfamily.Wrap* — use descriptive namespaced codes",
			AutoFix:     false,
		},
		{
			ID:          "D011",
			Name:        "nil-payload-event",
			Category:    "consistency",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Event created with nil payload — cannot be decoded, provides no audit trail",
			AutoFix:     false,
		},
		{
			ID:          "D012",
			Name:        "raw-print-in-handler",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "low",
			Description: "Raw fmt/log print in CQRS handler — use structured logging (slog)",
			AutoFix:     false,
		},
		{
			ID:          "D013",
			Name:        "missing-schema-version",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "low",
			Description: "Events created without event.WithSchemaVersion — schema evolution (upcasting) is impossible to add retroactively",
			AutoFix:     false,
		},
		{
			ID:          "D014",
			Name:        "event-payload-without-json-tags",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Event payload struct without json tags — Go field names used in JSON encoding",
			AutoFix:     false,
		},
		{
			ID:          "D015",
			Name:        "nullable-payload-fields",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Nullable pointer fields in event payloads — nil-dereference panic risk on decode",
			AutoFix:     false,
		},
	}
}

func architectureRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "E001",
			Name:        "layer-violation",
			Category:    "architecture",
			Severity:    "error",
			Confidence:  "high",
			Description: "Tier-0 module imports Tier-3+ module",
			AutoFix:     false,
		},
		{
			ID:          "E002",
			Name:        "circular-dependency",
			Category:    "architecture",
			Severity:    "error",
			Confidence:  "high",
			Description: "Two modules import each other",
			AutoFix:     false,
		},
		{
			ID:          "E003",
			Name:        "missing-module-boundary",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "low",
			Description: "All CQRS code in one package without boundaries",
			AutoFix:     false,
		},
		{
			ID:          "E004",
			Name:        "event-not-in-catalog",
			Category:    "architecture",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Event type emitted but not in catalog",
			AutoFix:     false,
		},
		{
			ID:          "E005",
			Name:        "command-without-handler",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Command type defined but never registered",
			AutoFix:     false,
		},
		{
			ID:          "E006",
			Name:        "event-without-projection",
			Category:    "architecture",
			Severity:    "info",
			Confidence:  "low",
			Description: "Event type emitted but no projection handles it",
			AutoFix:     false,
		},
		{
			ID:          "E007",
			Name:        "query-without-handler",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Query type defined but never registered",
			AutoFix:     false,
		},
		{
			ID:          "E008",
			Name:        "stack-preset-bypass",
			Category:    "architecture",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Stack presets available but decider.NewRepository called directly",
			AutoFix:     false,
		},
		{
			ID:          "E009",
			Name:        "no-http-integration",
			Category:    "architecture",
			Severity:    "info",
			Confidence:  "low",
			Description: "Command and query dispatchers present but no HTTP/gRPC transport",
			AutoFix:     false,
		},
		{
			ID:          "E010",
			Name:        "capture-without-validation",
			Category:    "architecture",
			Severity:    "info",
			Confidence:  "low",
			Description: "Events written to store without decider domain validation",
			AutoFix:     false,
		},
		{
			ID:          "E011",
			Name:        "excessive-adapter-layers",
			Category:    "architecture",
			Severity:    "info",
			Confidence:  "low",
			Description: "3+ Adapter types between command handlers and decider",
			AutoFix:     false,
		},
		{
			ID:          "E012",
			Name:        "dual-write-no-completion",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "low",
			Description: "Dual-write bus without feature flag or completion check",
			AutoFix:     false,
		},
		{
			ID:          "E013",
			Name:        "signing-disabled-by-default",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Signing/encryption imported but config Enabled: false",
			AutoFix:     false,
		},
		{
			ID:          "E014",
			Name:        "no-read-your-writes",
			Category:    "architecture",
			Severity:    "info",
			Confidence:  "low",
			Description: "Projectionhost used without drain/wait for read consistency",
			AutoFix:     false,
		},
		{
			ID:          "E015",
			Name:        "watermill-no-ordered-delivery",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "high",
			Description: "BlockPublishUntilSubscriberAck: false breaks ordered delivery",
			AutoFix:     false,
		},
		{
			ID:          "E016",
			Name:        "missing-health-checks",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Server-mode project without HealthCheck — Kubernetes probes need it",
			AutoFix:     false,
		},
		{
			ID:          "E017",
			Name:        "missing-graceful-shutdown",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "signal.Notify without GracefulClose/Stop — in-flight events lost on SIGTERM",
			AutoFix:     false,
		},
	}
}

func securityRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "S001",
			Name:        "hardcoded-secrets",
			Category:    "security",
			Severity:    "critical",
			Confidence:  "medium",
			Description: "Potential hardcoded secret in string literal",
			AutoFix:     false,
		},
		{
			ID:          "S002",
			Name:        "missing-encryption-for-sensitive-payloads",
			Category:    "security",
			Severity:    "error",
			Confidence:  "medium",
			Description: "PII event payloads without encryption middleware",
			AutoFix:     false,
		},
		{
			ID:          "S003",
			Name:        "missing-event-signing",
			Category:    "security",
			Severity:    "warning",
			Confidence:  "low",
			Description: "Event store without signing middleware",
			AutoFix:     false,
		},
		{
			ID:          "S005",
			Name:        "signing-available-but-disabled",
			Category:    "security",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Signing module imported but signer construction guarded by a default-false bool flag",
			AutoFix:     false,
		},
		{
			ID:          "S006",
			Name:        "financial-data-without-encryption",
			Category:    "security",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Financial data in structs without encryption module",
			AutoFix:     false,
		},
		{
			ID:          "S007",
			Name:        "in-memory-session-store",
			Category:    "security",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "In-memory session/token store loses state on restart",
			AutoFix:     false,
		},
		{
			ID:          "S008",
			Name:        "asymmetric-signing",
			Category:    "security",
			Severity:    "error",
			Confidence:  "high",
			Description: "SignMiddleware without VerifyMiddleware (or vice versa) — signing is decorative",
			AutoFix:     false,
		},
		{
			ID:          "S009",
			Name:        "asymmetric-encryption",
			Category:    "security",
			Severity:    "error",
			Confidence:  "high",
			Description: "EncryptMiddleware without DecryptMiddleware (or vice versa) — encrypted events break consumers",
			AutoFix:     false,
		},
		{
			ID:          "S010",
			Name:        "encryption-signing-mismatch",
			Category:    "security",
			Severity:    "error",
			Confidence:  "medium",
			Description: "Bus has encryption/signing middleware but store is not wrapped — events stored in cleartext",
			AutoFix:     false,
		},
	}
}

func testingRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "T001",
			Name:        "no-scenario-tests-for-deciders",
			Category:    "testing",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Project defines deciders but has no scenario.Given BDD tests",
			AutoFix:     false,
		},
		{
			ID:          "T002",
			Name:        "no-scenario-tests-for-projections",
			Category:    "testing",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Project defines projections but has no scenario.GivenProjection tests",
			AutoFix:     false,
		},
		{
			ID:          "T003",
			Name:        "no-eventtest-imports",
			Category:    "testing",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Project uses events but lacks eventtest fake stores/buses in tests",
			AutoFix:     false,
		},
		{
			ID:          "T004",
			Name:        "no-golden-snapshot-tests",
			Category:    "testing",
			Severity:    "info",
			Confidence:  "low",
			Description: "Catalog/documentation output has no snapshot tests",
			AutoFix:     false,
		},
		{
			ID:          "T005",
			Name:        "projection-without-error-test",
			Category:    "testing",
			Severity:    "info",
			Confidence:  "low",
			Description: "Projections have no error-path tests for malformed payloads",
			AutoFix:     false,
		},
		{
			ID:          "T006",
			Name:        "decider-without-conflict-test",
			Category:    "testing",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Decider scenario tests only cover happy paths, not conflict/error scenarios",
			AutoFix:     false,
		},
		{
			ID:          "T007",
			Name:        "no-event-roundtrip-test",
			Category:    "testing",
			Severity:    "info",
			Confidence:  "low",
			Description: "No save→load round-trip test for event stores",
			AutoFix:     false,
		},
		{
			ID:          "T008",
			Name:        "test-imports-production-store",
			Category:    "testing",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Test file imports a production store instead of eventtest/memory fakes",
			AutoFix:     false,
		},
	}
}

func adoptionRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "F001",
			Name:        "no-tombstone-softdelete",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Delete operations without event.MarkTombstone — consider tombstone soft-delete for audit trail",
			AutoFix:     false,
		},
		{
			ID:          "F002",
			Name:        "no-catalog-documentation",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "3+ event types but no catalog.NewBuilder — event documentation not generated",
			AutoFix:     false,
		},
		{
			ID:          "F003",
			Name:        "no-otel-tracing",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Server-mode project with no OpenTelemetry tracing",
			AutoFix:     false,
		},
		{
			ID:          "F004",
			Name:        "no-prometheus-metrics",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Server-mode project with no Prometheus metrics",
			AutoFix:     false,
		},
		{
			ID:          "F005",
			Name:        "no-schema-upcasters",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Evolving event schemas but no schema.NewUpcaster — version migrations not handled",
			AutoFix:     false,
		},
		{
			ID:          "F006",
			Name:        "no-encryption-for-sensitive-data",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Event payload with PII fields but no encryption module — sensitive data in plaintext",
			AutoFix:     false,
		},
		{
			ID:          "F007",
			Name:        "no-idempotency-middleware",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Command dispatcher without idempotency middleware — duplicate commands under at-least-once delivery",
			AutoFix:     false,
		},
		{
			ID:          "F008",
			Name:        "no-cbor-codec",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Event-heavy project using JSON codec — CBOR is ~35% smaller",
			AutoFix:     false,
		},
		{
			ID:          "F009",
			Name:        "no-scheduling-module",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Time-based patterns (timers, deadlines) but no scheduling module — hand-rolled timers are fragile",
			AutoFix:     false,
		},
		{
			ID:          "F010",
			Name:        "no-graph-projections",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Graph-traversal patterns but no graph module — recursive SQL CTEs are slow for deep traversals",
			AutoFix:     false,
		},
		{
			ID:          "F011",
			Name:        "no-relational-projections",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Multi-statement SQL projections without storage.RelationalProjection — manual writes lack atomicity",
			AutoFix:     false,
		},
		{
			ID:          "F012",
			Name:        "no-deriver-module",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Saga-like SubscribeAll + command dispatch but no deriver module",
			AutoFix:     false,
		},
		{
			ID:          "F013",
			Name:        "no-transport-module",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Manual HTTP handlers for dispatch but no transport module",
			AutoFix:     false,
		},
		{
			ID:          "F014",
			Name:        "no-kv-cache",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "kv.NewTypedStore without kv.NewCache — read model hits backing store on every read",
			AutoFix:     false,
		},
		{
			ID:          "F015",
			Name:        "no-metaengine",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Complex query patterns but no metaengine cost-based planner",
			AutoFix:     false,
		},
		{
			ID:          "F016",
			Name:        "no-listing-module",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Many aggregate types but no listing module — stream status tracking unavailable",
			AutoFix:     false,
		},
		{
			ID:          "F017",
			Name:        "no-dedup-module",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Bus subscriptions without dedup module — duplicate event delivery not handled at stream boundaries",
			AutoFix:     false,
		},
		{
			ID:          "F018",
			Name:        "metaengine-filteron-pushdown",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "medium",
			Description: "metaengine.FilterOn (closure-based) prevents SQL pushdown — use FilterOnField for WHERE-clause pushdown",
			AutoFix:     false,
		},
		{
			ID:          "F019",
			Name:        "metaengine-missing-volume-hint",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "metaengine queries lack Volume hint — cost-based planner cannot optimize engine selection",
			AutoFix:     false,
		},
		{
			ID:          "F020",
			Name:        "metaengine-sorton-pushdown",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "medium",
			Description: "metaengine.SortOn (closure-based) prevents SQL ORDER BY pushdown — use SortOnField for indexed sort",
			AutoFix:     false,
		},
		{
			ID:          "F021",
			Name:        "metaengine-write-amplification",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "metaengine query has many fold declarations — high write amplification may degrade ingest throughput",
			AutoFix:     false,
		},
	}
}
