package rules

// extraRulesNew returns metadata for newer rules (batch 2).
func extraRulesNew() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "A011",
			Name:        "inconsistent-json-key-casing-event-payloads",
			Category:    "api",
			Severity:    "info",
			Confidence:  "low",
			Description: "Event payload structs with mixed JSON key casing",
			AutoFix:     false,
		},
		{
			ID:          "A014",
			Name:        "deprecated-api-usage",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Calls to deprecated APIs (event.NewEvent, dispatcher.Register)",
			AutoFix:     false,
		},
		{
			ID:          "A017",
			Name:        "missing-snapshot-strategy",
			Category:    "api",
			Severity:    "info",
			Confidence:  "low",
			Description: "Repository without snapshot strategy — slow for large aggregates",
			AutoFix:     false,
		},
		{
			ID:          "B006",
			Name:        "duplicate-fk-stub-sql",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Duplicated foreign-key SQL — centralize as shared constant",
			AutoFix:     false,
		},
		{
			ID:          "B007",
			Name:        "repeated-handler-registration",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "3+ consecutive handler registrations — use table-driven approach",
			AutoFix:     false,
		},
		{
			ID:          "B009",
			Name:        "emit-function-boilerplate",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Hand-written emit/publish helper wrapping event.New + bus.Publish",
			AutoFix:     false,
		},
		{
			ID:          "B010",
			Name:        "catalog-event-list-boilerplate",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "3+ catalog.Event calls — use cqrs-gen to auto-generate",
			AutoFix:     false,
		},
		{
			ID:          "B012",
			Name:        "make-event-helper",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Hand-written makeEvent/newEvent helper — use event.New",
			AutoFix:     false,
		},
		{
			ID:          "B015",
			Name:        "missing-test-utilities",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "low",
			Description: "Project has tests but no testutil/eventtest imports",
			AutoFix:     false,
		},
		{
			ID:          "D003",
			Name:        "inconsistent-logging-library",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "high",
			Description: "Project mixes multiple logging libraries",
			AutoFix:     false,
		},
		{
			ID:          "D004",
			Name:        "inconsistent-json-key-casing",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Mixed camelCase and snake_case JSON tags",
			AutoFix:     false,
		},
		{
			ID:          "D005",
			Name:        "stale-documentation-version",
			Category:    "consistency",
			Severity:    "warning",
			Confidence:  "low",
			Description: "Documentation references different version than go.mod",
			AutoFix:     false,
		},
		{
			ID:          "E001",
			Name:        "layer-violation",
			Category:    "architecture",
			Severity:    "error",
			Confidence:  "high",
			Description: "Tier-0 module imports Tier-3+ module",
			AutoFix:     false,
		},
		{
			ID:          "E002",
			Name:        "circular-dependency",
			Category:    "architecture",
			Severity:    "error",
			Confidence:  "high",
			Description: "Two modules import each other",
			AutoFix:     false,
		},
		{
			ID:          "E003",
			Name:        "missing-module-boundary",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "low",
			Description: "All CQRS code in one package without boundaries",
			AutoFix:     false,
		},
		{
			ID:          "E006",
			Name:        "event-without-projection",
			Category:    "architecture",
			Severity:    "info",
			Confidence:  "low",
			Description: "Event type emitted but no projection handles it",
			AutoFix:     false,
		},
		{
			ID:          "E007",
			Name:        "query-without-handler",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Query type defined but never registered",
			AutoFix:     false,
		},
		{
			ID:          "S002",
			Name:        "missing-encryption-for-sensitive-payloads",
			Category:    "security",
			Severity:    "error",
			Confidence:  "medium",
			Description: "PII event payloads without encryption middleware",
			AutoFix:     false,
		},
		{
			ID:          "S003",
			Name:        "missing-event-signing",
			Category:    "security",
			Severity:    "warning",
			Confidence:  "low",
			Description: "Event store without signing middleware",
			AutoFix:     false,
		},
	}
}
