package rules

func boilerplateRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "B001",
			Name:        "single-event-helper",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Single-event helper function — use event.Single()",
			AutoFix:     false,
		},
		{
			ID:          "B002",
			Name:        "manual-repository-wiring",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Manual store+bus+repository wiring — use stack preset",
			AutoFix:     false,
		},
		{
			ID:          "B003",
			Name:        "subscribeall-large-switch",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "medium",
			Description: "SubscribeAll with >5 switch cases — split into projections",
			AutoFix:     false,
		},
		{
			ID:          "B004",
			Name:        "command-constructor-boilerplate",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Command with many fields — use cqrs-gen",
			AutoFix:     false,
		},
		{
			ID:          "B005",
			Name:        "fold-switch-boilerplate",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Fold uses switch — consider decider.StrictApply",
			AutoFix:     false,
		},
		{
			ID:          "B006",
			Name:        "duplicate-fk-stub-sql",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Duplicated foreign-key SQL — centralize as shared constant",
			AutoFix:     false,
		},
		{
			ID:          "B007",
			Name:        "repeated-handler-registration",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "3+ consecutive handler registrations — use table-driven approach",
			AutoFix:     false,
		},
		{
			ID:          "B008",
			Name:        "manual-retry-implementation",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Manual retry loop — use retry.Do",
			AutoFix:     false,
		},
		{
			ID:          "B009",
			Name:        "emit-function-boilerplate",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Hand-written emit/publish helper wrapping event.New + bus.Publish",
			AutoFix:     false,
		},
		{
			ID:          "B010",
			Name:        "catalog-event-list-boilerplate",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "3+ catalog.Event calls — use cqrs-gen to auto-generate",
			AutoFix:     false,
		},
		{
			ID:          "B011",
			Name:        "must-marshal-helper",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "mustMarshal helper — use event.New",
			AutoFix:     false,
		},
		{
			ID:          "B012",
			Name:        "make-event-helper",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Hand-written makeEvent/newEvent helper — use event.New",
			AutoFix:     false,
		},
		{
			ID:          "B013",
			Name:        "missing-correlation-enricher",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Repository without correlation enricher",
			AutoFix:     false,
		},
		{
			ID:          "B014",
			Name:        "missing-otel-middleware",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "low",
			Description: "Bus/dispatcher lacks OTel tracing middleware",
			AutoFix:     false,
		},
		{
			ID:          "B015",
			Name:        "missing-test-utilities",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "low",
			Description: "Project has tests but no testutil/eventtest imports",
			AutoFix:     false,
		},
		{
			ID:          "B016",
			Name:        "manual-checkpoint-replay",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Manual checkpoint table + journal replay loop — use projectionhost.Host",
			AutoFix:     false,
		},
		{
			ID:          "B017",
			Name:        "manual-readmodel-rebuild",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Read model rebuilt from scratch on startup — use incremental catch-up with checkpoints",
			AutoFix:     false,
		},
		{
			ID:          "B018",
			Name:        "repeated-subscribe-boilerplate",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "medium",
			Description: "3+ bus.Subscribe calls in same file — extract into table-driven registration",
			AutoFix:     false,
		},
		{
			ID:          "B019",
			Name:        "load-in-subscribeall",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "high",
			Description: "repo.Load inside SubscribeAll handler — O(N^2) replay",
			AutoFix:     false,
		},
		{
			ID:          "B020",
			Name:        "manual-legacy-upcasting",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Manual field upcasting in decode function — use schema.NewUpcaster",
			AutoFix:     false,
		},
		{
			ID:          "B021",
			Name:        "fold-without-strictapply",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Fold function silently ignores unknown events — use decider.StrictApply",
			AutoFix:     false,
		},
		{
			ID:          "B022",
			Name:        "manual-correlation-enricher",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Custom enricher instead of decider.CommandCausalityEnricher",
			AutoFix:     false,
		},
		{
			ID:          "B023",
			Name:        "missing-command-middleware",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Command dispatcher has no middleware — panics in handlers crash the process",
			AutoFix:     false,
		},
		{
			ID:          "B024",
			Name:        "missing-bus-recovery",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Event bus has no recovery middleware — panics in handlers crash the bus",
			AutoFix:     false,
		},
		{
			ID:          "B025",
			Name:        "missing-state-cache",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "low",
			Description: "Repository without WithStateCache — hot streams benefit from incremental loads",
			AutoFix:     false,
		},
		{
			ID:          "B026",
			Name:        "missing-catalog-registration",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "medium",
			Description: "3+ event types but no catalog import — documentation generation unavailable",
			AutoFix:     false,
		},
		{
			ID:          "B027",
			Name:        "hardcoded-stream-type",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "low",
			Description: "Hardcoded stream-type string literal — use a constant for consistency",
			AutoFix:     false,
		},
		{
			ID:          "B028",
			Name:        "manual-goroutine-dispatch",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "low",
			Description: "Manual goroutine dispatch of command — deriver.AsHandler provides idempotent dispatch",
			AutoFix:     false,
		},
		{
			ID:          "B029",
			Name:        "missing-retry-middleware",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "low",
			Description: "Bus/dispatcher without retry middleware — transient failures propagate to callers",
			AutoFix:     false,
		},
		{
			ID:          "B030",
			Name:        "missing-circuit-breaker",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "low",
			Description: "Bus/dispatcher without circuit breaker middleware — cascading failures not isolated",
			AutoFix:     false,
		},
		{
			ID:          "B031",
			Name:        "missing-dead-letter-config",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "low",
			Description: "projectionhost.New without WithDeadLetterStore — poison events cause terminal failure",
			AutoFix:     false,
		},
	}
}
