package rules

func adoptionRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "F001",
			Name:        "no-domain-delete-event",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Delete operations without a domain deletion event — consider emitting a deletion event (e.g., \"user.deleted\") for audit trail (ADR-0114)",
			AutoFix:     false,
		},
		{
			ID:          "F002",
			Name:        "no-catalog-documentation",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "3+ event types but no catalog.NewBuilder — event documentation not generated",
			AutoFix:     false,
		},
		{
			ID:          "F003",
			Name:        "no-otel-tracing",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Server-mode project with no OpenTelemetry tracing",
			AutoFix:     false,
		},
		{
			ID:          "F004",
			Name:        "no-prometheus-metrics",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Server-mode project with no Prometheus metrics",
			AutoFix:     false,
		},
		{
			ID:          "F005",
			Name:        "no-schema-upcasters",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Evolving event schemas but no schema.NewUpcaster — version migrations not handled",
			AutoFix:     false,
		},
		{
			ID:          "F006",
			Name:        "no-encryption-for-sensitive-data",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Event payload with PII fields but no encryption module — sensitive data in plaintext",
			AutoFix:     false,
		},
		{
			ID:          "F007",
			Name:        "no-idempotency-middleware",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Command dispatcher without idempotency middleware — duplicate commands under at-least-once delivery",
			AutoFix:     false,
		},
		{
			ID:          "F008",
			Name:        "no-cbor-codec",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Event-heavy project using JSON codec — CBOR is ~35% smaller",
			AutoFix:     false,
		},
		{
			ID:          "F009",
			Name:        "no-scheduling-module",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Time-based patterns (timers, deadlines) but no scheduling module — hand-rolled timers are fragile",
			AutoFix:     false,
		},
		{
			ID:          "F010",
			Name:        "no-graph-projections",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Graph-traversal patterns but no graph module — recursive SQL CTEs are slow for deep traversals",
			AutoFix:     false,
		},
		{
			ID:          "F011",
			Name:        "no-relational-projections",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Multi-statement SQL projections without storage.RelationalProjection — manual writes lack atomicity",
			AutoFix:     false,
		},
		{
			ID:          "F012",
			Name:        "no-deriver-module",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Saga-like SubscribeAll + command dispatch but no deriver module",
			AutoFix:     false,
		},
		{
			ID:          "F013",
			Name:        "no-transport-module",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Manual HTTP handlers for dispatch but no delivery module (watermill bridge, go-sse, or cqrs-htmx)",
			AutoFix:     false,
		},
		{
			ID:          "F014",
			Name:        "no-kv-cache",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "kv.NewTypedStore without kv.NewCache — read model hits backing store on every read",
			AutoFix:     false,
		},
		{
			ID:          "F015",
			Name:        "no-metaengine",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "3+ query registrations but no metaengine cost-based planner — SQL pushdown and layout optimization unavailable",
			AutoFix:     false,
		},
		{
			ID:          "F016",
			Name:        "no-listing-module",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Many aggregate types but no listing module — stream status tracking unavailable",
			AutoFix:     false,
		},
		{
			ID:          "F017",
			Name:        "no-dedup-module",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Bus subscriptions without dedup module — duplicate event delivery not handled at stream boundaries",
			AutoFix:     false,
		},
		{
			ID:          "F018",
			Name:        "metaengine-filteron-pushdown",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "medium",
			Description: "metaengine.FilterOn (closure-based) prevents SQL pushdown — use FilterOnField for WHERE-clause pushdown",
			AutoFix:     false,
		},
		{
			ID:          "F019",
			Name:        "metaengine-missing-volume-hint",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "metaengine queries lack Volume hint — cost-based planner cannot optimize engine selection",
			AutoFix:     false,
		},
		{
			ID:          "F020",
			Name:        "metaengine-sorton-pushdown",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "medium",
			Description: "metaengine.SortOn (closure-based) prevents SQL ORDER BY pushdown — use SortOnField for indexed sort",
			AutoFix:     false,
		},
		{
			ID:          "F021",
			Name:        "metaengine-write-amplification",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "metaengine query has many fold declarations — high write amplification may degrade ingest throughput",
			AutoFix:     false,
		},
		{
			ID:          "F022",
			Name:        "manual-sort-no-pushdown",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Manual in-memory sorting (sort.Slice/slices.SortFunc) with a SQL store but no metaengine — all rows loaded into Go memory for sorting",
			AutoFix:     false,
		},
		{
			ID:          "F023",
			Name:        "manual-filter-no-pushdown",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Manual in-memory filtering (for-range + if + append) with a SQL store but no metaengine — all rows loaded into Go memory for filtering",
			AutoFix:     false,
		},
		{
			ID:          "F024",
			Name:        "manual-pagination-no-pushdown",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Manual pagination (slice[offset:offset+limit]) with a SQL store but no metaengine — all rows loaded into Go memory before slicing",
			AutoFix:     false,
		},
		{
			ID:          "F025",
			Name:        "manual-count-no-counter-adt",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Manual count/aggregation (for-range + count++/sum +=) with a SQL store but no metaengine — full collection scanned for every count",
			AutoFix:     false,
		},
		{
			ID:          "F026",
			Name:        "no-metaengine-prefetch",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "metaengine.NewReader used but WithPrefetch never called — every Scan/Get hits the underlying store individually",
			AutoFix:     false,
		},
		{
			ID:          "F027",
			Name:        "missing-otel-sdk-init",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Project imports OTel but never calls Setup() — tracing is configured but inactive",
			AutoFix:     false,
		},
		{
			ID:          "F028",
			Name:        "missing-slog-setdefault",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "low",
			Description: "Project uses slog but never calls slog.SetDefault — default logger is unconfigured",
			AutoFix:     false,
		},
		{
			ID:          "F029",
			Name:        "missing-span-creation",
			Category:    "adoption",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Project has OTel but no tracing middleware — handlers are not instrumented",
			AutoFix:     false,
		},
		{
			ID:          "F030",
			Name:        "deprecated-transport-import",
			Category:    "adoption",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Import of deprecated transport/* module — removed at v5; migrate to go-sse, watermill bridge, or cqrs-htmx (ADR-0127)",
			AutoFix:     false,
		},
	}
}
