package rules

func correctnessRulesPart1() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "C001",
			Name:        "missing-tx-commit",
			Category:    "correctness",
			Severity:    "critical",
			Confidence:  "high",
			Description: "Transaction wrapper returns nil instead of tx.Commit()",
			AutoFix:     true,
			DocURL:      "https://github.com/larsartmann/go-cqrs-lite/blob/main/cmd/cqrs-lint/RULES.md#c001",
		},
		{
			ID:          "C002",
			Name:        "broken-command-id",
			Category:    "correctness",
			Severity:    "critical",
			Confidence:  "high",
			Description: "Command ID() returns zero value — breaks idempotency",
			AutoFix:     false,
		},
		{
			ID:          "C003",
			Name:        "silent-unknown-event-fold",
			Category:    "correctness",
			Severity:    "error",
			Confidence:  "high",
			Description: "Fold function silently ignores unknown event types",
			AutoFix:     true,
		},
		{
			ID:          "C004",
			Name:        "checkpoint-before-async-complete",
			Category:    "correctness",
			Severity:    "error",
			Confidence:  "medium",
			Description: "Projection launches async work — checkpoint may save before completion",
			AutoFix:     false,
		},
		{
			ID:          "C005",
			Name:        "raw-json-unmarshal-payload",
			Category:    "correctness",
			Severity:    "error",
			Confidence:  "high",
			Description: "Raw json.Unmarshal on event payload instead of DecodePayloadAuto",
			AutoFix:     false,
		},
		{
			ID:          "C006",
			Name:        "manual-version-arithmetic",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Manual event.Version(x.Int()+1) instead of x.Increment()",
			AutoFix:     true,
		},
		{
			ID:          "C007",
			Name:        "time-now-in-decider",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "time.Now() inside decider — non-deterministic",
			AutoFix:     false,
		},
		{
			ID:          "C008",
			Name:        "float64-for-money",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "float64 field with monetary name — use decimal or cents",
			AutoFix:     false,
			DocURL:      "https://github.com/larsartmann/go-cqrs-lite/blob/main/cmd/cqrs-lint/RULES.md#c008",
		},
		{
			ID:          "C009",
			Name:        "panic-in-production",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "panic() in production code — use error returns",
			AutoFix:     false,
		},
		{
			ID:          "C010",
			Name:        "swallowed-error-in-fold",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Error from decode/unmarshal discarded in fold",
			AutoFix:     false,
			DocURL:      "https://github.com/larsartmann/go-cqrs-lite/blob/main/cmd/cqrs-lint/RULES.md#c010",
		},
		{
			ID:          "C011",
			Name:        "nondeterministic-decider",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "low",
			Description: "rand.* call inside decider — non-deterministic replay",
			AutoFix:     false,
		},
		{
			ID:          "C012",
			Name:        "missing-error-return-in-with-tx",
			Category:    "correctness",
			Severity:    "critical",
			Confidence:  "high",
			Description: "withTx ignores body error — failures silently lost",
			AutoFix:     false,
		},
		{
			ID:          "C013",
			Name:        "time-time-in-event-payload",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "time.Time field in event payload loses timezone via CBOR epoch encoding",
			AutoFix:     false,
			DocURL:      "https://github.com/larsartmann/go-cqrs-lite/blob/main/docs/TIMEZONE_HANDLING.md",
		},
		{
			ID:          "C014",
			Name:        "time-local-usage",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "time.Local causes silent data corruption across timezone boundaries",
			AutoFix:     false,
		},
		{
			ID:          "C015",
			Name:        "unchecked-close",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Close() error discarded — resource leak or silent data loss risk",
			AutoFix:     false,
		},
		{
			ID:          "C016",
			Name:        "background-in-handler",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "context.Background()/TODO() in a handler with a ctx param — discards cancellation, timeouts, tracing",
			AutoFix:     false,
		},
		{
			ID:          "C017",
			Name:        "inmem-store-persistent-eventstore",
			Category:    "correctness",
			Severity:    "error",
			Confidence:  "high",
			Description: "In-memory snapshot/checkpoint/dead-letter/timer store with persistent event store — lost on restart",
			AutoFix:     false,
			DocURL:      "https://github.com/larsartmann/go-cqrs-lite/blob/main/cmd/cqrs-lint/RULES.md#c017",
		},
		{
			ID:          "C018",
			Name:        "silent-journal-fallback",
			Category:    "correctness",
			Severity:    "error",
			Confidence:  "high",
			Description: "memory.NewMemoryStore() used as journal fallback — projections replay from empty journal",
			AutoFix:     false,
		},
		{
			ID:          "C019",
			Name:        "multiple-repos-same-aggregate",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Multiple Repository instances for the same aggregate type — wastes singleflight/cache",
			AutoFix:     false,
		},
		{
			ID:          "C020",
			Name:        "panic-in-handler",
			Category:    "correctness",
			Severity:    "error",
			Confidence:  "high",
			Description: "panic() in bus.Subscribe/SubscribeAll handler — crashes the bus/projection host",
			AutoFix:     false,
		},
		{
			ID:          "C021",
			Name:        "mutex-held-during-decode",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Payload decode while mutex is held — serializes all event processing",
			AutoFix:     false,
		},
	}
}
