package rules

func boilerplateRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "B001",
			Name:        "single-event-helper",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Single-event helper function — use event.Single()",
			AutoFix:     false,
		},
		{
			ID:          "B002",
			Name:        "manual-repository-wiring",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Manual store+bus+repository wiring — use stack preset",
			AutoFix:     false,
		},
		{
			ID:          "B003",
			Name:        "subscribeall-large-switch",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "medium",
			Description: "SubscribeAll with >5 switch cases — split into projections",
			AutoFix:     false,
		},
		{
			ID:          "B004",
			Name:        "command-constructor-boilerplate",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Command with many fields — use cqrs-gen",
			AutoFix:     false,
		},
		{
			ID:          "B005",
			Name:        "fold-switch-boilerplate",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Fold uses switch — consider decider.StrictApply",
			AutoFix:     false,
		},
		{
			ID:          "B006",
			Name:        "duplicate-fk-stub-sql",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Duplicated foreign-key SQL — centralize as shared constant",
			AutoFix:     false,
		},
		{
			ID:          "B007",
			Name:        "repeated-handler-registration",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "3+ consecutive handler registrations — use table-driven approach",
			AutoFix:     false,
		},
		{
			ID:          "B008",
			Name:        "manual-retry-implementation",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Manual retry loop — use retry.Do",
			AutoFix:     false,
		},
		{
			ID:          "B009",
			Name:        "emit-function-boilerplate",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Hand-written emit/publish helper wrapping event.New + bus.Publish",
			AutoFix:     false,
		},
		{
			ID:          "B010",
			Name:        "catalog-event-list-boilerplate",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "3+ catalog.Event calls — use cqrs-gen to auto-generate",
			AutoFix:     false,
		},
		{
			ID:          "B011",
			Name:        "must-marshal-helper",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "mustMarshal helper — use event.New",
			AutoFix:     false,
		},
		{
			ID:          "B012",
			Name:        "make-event-helper",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Hand-written makeEvent/newEvent helper — use event.New",
			AutoFix:     false,
		},
		{
			ID:          "B013",
			Name:        "missing-correlation-enricher",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Repository without correlation enricher",
			AutoFix:     false,
		},
		{
			ID:          "B014",
			Name:        "missing-otel-middleware",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "low",
			Description: "Bus/dispatcher lacks OTel tracing middleware",
			AutoFix:     false,
		},
		{
			ID:          "B015",
			Name:        "missing-test-utilities",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "low",
			Description: "Project has tests but no testutil/eventtest imports",
			AutoFix:     false,
		},
	}
}

func consistencyRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "D001",
			Name:        "inconsistent-event-naming",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Mixed dot notation and PascalCase event types",
			AutoFix:     false,
		},
		{
			ID:          "D002",
			Name:        "inconsistent-json-casing",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "low",
			Description: "Mixed camelCase and snake_case JSON tags",
			AutoFix:     false,
		},
		{
			ID:          "D003",
			Name:        "inconsistent-logging-library",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "high",
			Description: "Project mixes multiple logging libraries",
			AutoFix:     false,
		},
		{
			ID:          "D005",
			Name:        "stale-documentation-version",
			Category:    "consistency",
			Severity:    "warning",
			Confidence:  "low",
			Description: "Documentation references different version than go.mod",
			AutoFix:     false,
		},
		{
			ID:          "D006",
			Name:        "missing-errorfamily",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "medium",
			Description: "errors.New or fmt.Errorf without %w bypasses the 6-family error taxonomy",
			AutoFix:     false,
		},
	}
}

func architectureRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "E001",
			Name:        "layer-violation",
			Category:    "architecture",
			Severity:    "error",
			Confidence:  "high",
			Description: "Tier-0 module imports Tier-3+ module",
			AutoFix:     false,
		},
		{
			ID:          "E002",
			Name:        "circular-dependency",
			Category:    "architecture",
			Severity:    "error",
			Confidence:  "high",
			Description: "Two modules import each other",
			AutoFix:     false,
		},
		{
			ID:          "E003",
			Name:        "missing-module-boundary",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "low",
			Description: "All CQRS code in one package without boundaries",
			AutoFix:     false,
		},
		{
			ID:          "E004",
			Name:        "event-not-in-catalog",
			Category:    "architecture",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Event type emitted but not in catalog",
			AutoFix:     false,
		},
		{
			ID:          "E005",
			Name:        "command-without-handler",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Command type defined but never registered",
			AutoFix:     false,
		},
		{
			ID:          "E006",
			Name:        "event-without-projection",
			Category:    "architecture",
			Severity:    "info",
			Confidence:  "low",
			Description: "Event type emitted but no projection handles it",
			AutoFix:     false,
		},
		{
			ID:          "E007",
			Name:        "query-without-handler",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Query type defined but never registered",
			AutoFix:     false,
		},
	}
}

func securityRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "S001",
			Name:        "hardcoded-secrets",
			Category:    "security",
			Severity:    "critical",
			Confidence:  "medium",
			Description: "Potential hardcoded secret in string literal",
			AutoFix:     false,
		},
		{
			ID:          "S002",
			Name:        "missing-encryption-for-sensitive-payloads",
			Category:    "security",
			Severity:    "error",
			Confidence:  "medium",
			Description: "PII event payloads without encryption middleware",
			AutoFix:     false,
		},
		{
			ID:          "S003",
			Name:        "missing-event-signing",
			Category:    "security",
			Severity:    "warning",
			Confidence:  "low",
			Description: "Event store without signing middleware",
			AutoFix:     false,
		},
	}
}
