package rules

func apiRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "A001",
			Name:        "manual-command-interface",
			Category:    "api",
			Severity:    "error",
			Confidence:  "high",
			Description: "Manual Type()/ID()/StreamID() instead of BasicCommand embedding",
			AutoFix:     false,
		},
		{
			ID:          "A002",
			Name:        "newevent-manual-marshal",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "high",
			Description: "event.NewEvent with json.Marshal — use event.New for auto-marshal",
			AutoFix:     false,
		},
		{
			ID:          "A003",
			Name:        "explicit-codec-in-decode",
			Category:    "api",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Explicit codec in DecodePayload — use DecodePayloadAuto",
			AutoFix:     false,
		},
		{
			ID:          "A004",
			Name:        "untyped-dispatch-register",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Untyped handler with type assertion — use RegisterTyped",
			AutoFix:     false,
		},
		{
			ID:          "A005",
			Name:        "custom-projection-runner",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Manual bus.SubscribeAll without projectionhost",
			AutoFix:     false,
		},
		{
			ID:          "A006",
			Name:        "adapter-layer-wrapping",
			Category:    "api",
			Severity:    "info",
			Confidence:  "low",
			Description: "WrapEvent/UnwrapEvent adapter methods",
			AutoFix:     false,
		},
		{
			ID:          "A007",
			Name:        "dual-model-oo-functional",
			Category:    "api",
			Severity:    "error",
			Confidence:  "medium",
			Description: "Both OO aggregates and functional deciders",
			AutoFix:     false,
		},
		{
			ID:          "A008",
			Name:        "parallel-type-system",
			Category:    "api",
			Severity:    "error",
			Confidence:  "high",
			Description: "Custom StreamID/Version types duplicating go-cqrs-lite",
			AutoFix:     false,
		},
		{
			ID:          "A009",
			Name:        "missing-stack-preset",
			Category:    "api",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Project does not use a stack/ preset",
			AutoFix:     false,
		},
		{
			ID:          "A010",
			Name:        "custom-error-types",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "low",
			Description: "Custom error interface duplicating go-error-family",
			AutoFix:     false,
		},
		{
			ID:          "A011",
			Name:        "inconsistent-json-key-casing-event-payloads",
			Category:    "api",
			Severity:    "info",
			Confidence:  "low",
			Description: "Event payload structs with mixed JSON key casing",
			AutoFix:     false,
		},
		{
			ID:          "A012",
			Name:        "missing-tombstone-handling",
			Category:    "api",
			Severity:    "info",
			Confidence:  "low",
			Description: "Fold function does not check for tombstone events",
			AutoFix:     false,
		},
		{
			ID:          "A013",
			Name:        "pointer-vs-value-basic-command",
			Category:    "api",
			Severity:    "info",
			Confidence:  "high",
			Description: "Command embeds *BasicCommand (pointer) instead of value",
			AutoFix:     false,
		},
		{
			ID:          "A014",
			Name:        "deprecated-api-usage",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Calls to deprecated APIs (event.NewEvent, dispatcher.Register)",
			AutoFix:     false,
		},
		{
			ID:          "A015",
			Name:        "global-mutable-state",
			Category:    "api",
			Severity:    "error",
			Confidence:  "medium",
			Description: "Global mutable variable — race condition risk",
			AutoFix:     false,
		},
		{
			ID:          "A016",
			Name:        "missing-idempotency-middleware",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "low",
			Description: "Command dispatcher lacks idempotency middleware",
			AutoFix:     false,
		},
		{
			ID:          "A017",
			Name:        "missing-snapshot-strategy",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Repository without snapshot strategy — slow for large aggregates",
			AutoFix:     false,
		},
		{
			ID:          "A018",
			Name:        "no-actual-event-sourcing",
			Category:    "api",
			Severity:    "info",
			Confidence:  "high",
			Description: "Imports go-cqrs-lite but never calls Save/Publish",
			AutoFix:     false,
		},
		{
			ID:          "A019",
			Name:        "vendored-cqrs",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Vendored copy of go-cqrs-lite detected",
			AutoFix:     false,
		},
		{
			ID:          "A020",
			Name:        "custom-event-bus",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Custom event.Bus implementation — use watermill.NewEventBus() or the library's memory bus",
			AutoFix:     false,
		},
		{
			ID:          "A021",
			Name:        "custom-event-store",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Custom event.Store implementation — use storage/memory or a SQL/Pebble backend",
			AutoFix:     false,
		},
		{
			ID:          "A022",
			Name:        "raw-otel-tracer",
			Category:    "api",
			Severity:    "info",
			Confidence:  "high",
			Description: "Raw otel.Tracer/Meter instead of cqrsotel.NewTracer/NewMeter",
			AutoFix:     false,
		},
		{
			ID:          "A023",
			Name:        "custom-snapshot-store",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Custom snapshot store — use storage/memory.NewMemorySnapshotStore()",
			AutoFix:     false,
		},
		{
			ID:          "A024",
			Name:        "decorative-event-sourcing",
			Category:    "api",
			Severity:    "info",
			Confidence:  "high",
			Description: "Imports event/ and decider/ but never creates events or wires a repository",
			AutoFix:     false,
		},
		{
			ID:          "A025",
			Name:        "command-query-no-events",
			Category:    "api",
			Severity:    "info",
			Confidence:  "low",
			Description: "Command/query dispatchers without event sourcing — may miss audit trail and replay",
			AutoFix:     false,
		},
		{
			ID:          "A026",
			Name:        "event-bus-only",
			Category:    "api",
			Severity:    "info",
			Confidence:  "low",
			Description: "Event/ and watermill only — no command, decider, or query (bare event bus)",
			AutoFix:     false,
		},
		{
			ID:          "A027",
			Name:        "repeated-withcodec",
			Category:    "api",
			Severity:    "info",
			Confidence:  "high",
			Description: "event.WithCodec called 3+ times in one file — set codec once via event.DefaultCodec",
			AutoFix:     false,
		},
		{
			ID:          "A029",
			Name:        "usepublish-stub",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "high",
			Description: "UsePublish method is a stub returning nil — publish middleware chain discarded",
			AutoFix:     false,
		},
		{
			ID:          "A030",
			Name:        "incomplete-snapshot-config",
			Category:    "api",
			Severity:    "error",
			Confidence:  "high",
			Description: "WithSnapshotStrategy without WithSnapshotStore — ErrIncompleteSnapshotConfig at runtime",
			AutoFix:     false,
		},
		{
			ID:          "A032",
			Name:        "string-id-instead-of-branded",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Struct field named *ID with type string/int — use id.Of[T] branded ID for type safety",
			AutoFix:     false,
		},
		{
			ID:          "A033",
			Name:        "branded-id-string-roundtrip",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "high",
			Description: "id.Parse[T](x.String()) — pointless branded-ID roundtrip that discards the typed value and re-runs validation",
			AutoFix:     false,
		},
		{
			ID:          "A034",
			Name:        "metaengine-execute-untyped",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "metaengine.Execute returns an untyped result (any) — requires a runtime type assertion that can panic",
			AutoFix:     false,
		},
	}
}
