package rules

func securityRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "S001",
			Name:        "hardcoded-secrets",
			Category:    "security",
			Severity:    "critical",
			Confidence:  "medium",
			Description: "Potential hardcoded secret in string literal",
			AutoFix:     false,
		},
		{
			ID:          "S002",
			Name:        "missing-encryption-for-sensitive-payloads",
			Category:    "security",
			Severity:    "error",
			Confidence:  "medium",
			Description: "PII event payloads without encryption middleware",
			AutoFix:     false,
			DocURL:      "https://github.com/larsartmann/go-cqrs-lite/blob/main/cmd/cqrs-lint/RULES.md#s002",
		},
		{
			ID:          "S003",
			Name:        "missing-event-signing",
			Category:    "security",
			Severity:    "warning",
			Confidence:  "low",
			Description: "Event store without signing middleware",
			AutoFix:     false,
		},
		{
			ID:          "S005",
			Name:        "signing-available-but-disabled",
			Category:    "security",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Signing module imported but signer construction guarded by a default-false bool flag",
			AutoFix:     false,
		},
		{
			ID:          "S006",
			Name:        "financial-data-without-encryption",
			Category:    "security",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Financial data in structs without encryption module",
			AutoFix:     false,
		},
		{
			ID:          "S007",
			Name:        "in-memory-session-store",
			Category:    "security",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "In-memory session/token store loses state on restart",
			AutoFix:     false,
		},
		{
			ID:          "S008",
			Name:        "asymmetric-signing",
			Category:    "security",
			Severity:    "error",
			Confidence:  "high",
			Description: "SignMiddleware without VerifyMiddleware (or vice versa) — signing is decorative",
			AutoFix:     false,
		},
		{
			ID:          "S009",
			Name:        "asymmetric-encryption",
			Category:    "security",
			Severity:    "error",
			Confidence:  "high",
			Description: "EncryptMiddleware without DecryptMiddleware (or vice versa) — encrypted events break consumers",
			AutoFix:     false,
		},
		{
			ID:          "S010",
			Name:        "encryption-signing-mismatch",
			Category:    "security",
			Severity:    "error",
			Confidence:  "medium",
			Description: "Bus has encryption/signing middleware but store is not wrapped — events stored in cleartext",
			AutoFix:     false,
			DocURL:      "https://github.com/larsartmann/go-cqrs-lite/blob/main/cmd/cqrs-lint/RULES.md#s010",
		},
		{
			ID:          "S011",
			Name:        "pii-without-encryption",
			Category:    "security",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "PII field in event payload without bus encryption middleware — data persisted in cleartext to event store",
			AutoFix:     false,
		},
	}
}

