// Package rules provides centralized rule registration for cqrs-lint.
package rules

type RuleInfo struct {
	ID          string
	Name        string
	Category    string
	Severity    string
	Confidence  string
	Description string
	AutoFix     bool
}

// AllRules returns metadata for all available rules, organized by category.
func AllRules() []RuleInfo {
	return append(append(append(append(append(
		correctnessRules(),
		apiRules()...,
	),
		boilerplateRules()...),
		consistencyRules()...),
		architectureRules()...),
		securityRules()...)
}

func correctnessRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "C001",
			Name:        "missing-tx-commit",
			Category:    "correctness",
			Severity:    "critical",
			Confidence:  "high",
			Description: "Transaction wrapper returns nil instead of tx.Commit()",
			AutoFix:     true,
		},
		{
			ID:          "C002",
			Name:        "broken-command-id",
			Category:    "correctness",
			Severity:    "critical",
			Confidence:  "high",
			Description: "Command ID() returns zero value — breaks idempotency",
			AutoFix:     false,
		},
		{
			ID:          "C003",
			Name:        "silent-unknown-event-fold",
			Category:    "correctness",
			Severity:    "error",
			Confidence:  "high",
			Description: "Fold function silently ignores unknown event types",
			AutoFix:     true,
		},
		{
			ID:          "C004",
			Name:        "checkpoint-before-async-complete",
			Category:    "correctness",
			Severity:    "error",
			Confidence:  "medium",
			Description: "Projection launches async work — checkpoint may save before completion",
			AutoFix:     false,
		},
		{
			ID:          "C005",
			Name:        "raw-json-unmarshal-payload",
			Category:    "correctness",
			Severity:    "error",
			Confidence:  "high",
			Description: "Raw json.Unmarshal on event payload instead of DecodePayloadAuto",
			AutoFix:     false,
		},
		{
			ID:          "C006",
			Name:        "manual-version-arithmetic",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Manual event.Version(x.Int()+1) instead of x.Increment()",
			AutoFix:     true,
		},
		{
			ID:          "C007",
			Name:        "time-now-in-decider",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "time.Now() inside decider — non-deterministic",
			AutoFix:     false,
		},
		{
			ID:          "C008",
			Name:        "float64-for-money",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "float64 field with monetary name — use decimal or cents",
			AutoFix:     false,
		},
		{
			ID:          "C009",
			Name:        "panic-in-production",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "panic() in production code — use error returns",
			AutoFix:     false,
		},
		{
			ID:          "C010",
			Name:        "swallowed-error-in-fold",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Error from decode/unmarshal discarded in fold",
			AutoFix:     false,
		},
		{
			ID:          "C011",
			Name:        "nondeterministic-decider",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "low",
			Description: "rand.* call inside decider — non-deterministic replay",
			AutoFix:     false,
		},
		{
			ID:          "C012",
			Name:        "missing-error-return-in-with-tx",
			Category:    "correctness",
			Severity:    "critical",
			Confidence:  "high",
			Description: "withTx ignores body error — failures silently lost",
			AutoFix:     false,
		},
		{
			ID:          "C013",
			Name:        "time-time-in-event-payload",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "time.Time field in event payload loses timezone via CBOR epoch encoding",
			AutoFix:     false,
		},
		{
			ID:          "C014",
			Name:        "time-local-usage",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "time.Local causes silent data corruption across timezone boundaries",
			AutoFix:     false,
		},
		{
			ID:          "C015",
			Name:        "unchecked-close",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Close() error discarded — resource leak or silent data loss risk",
			AutoFix:     false,
		},
		{
			ID:          "C016",
			Name:        "background-in-handler",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "context.Background()/TODO() in a handler with a ctx param — discards cancellation, timeouts, tracing",
			AutoFix:     false,
		},
	}
}

func apiRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "A001",
			Name:        "manual-command-interface",
			Category:    "api",
			Severity:    "error",
			Confidence:  "high",
			Description: "Manual Type()/ID()/StreamID() instead of BasicCommand embedding",
			AutoFix:     false,
		},
		{
			ID:          "A002",
			Name:        "newevent-manual-marshal",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "high",
			Description: "event.NewEvent with json.Marshal — use event.New for auto-marshal",
			AutoFix:     false,
		},
		{
			ID:          "A003",
			Name:        "explicit-codec-in-decode",
			Category:    "api",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Explicit codec in DecodePayload — use DecodePayloadAuto",
			AutoFix:     false,
		},
		{
			ID:          "A004",
			Name:        "untyped-dispatch-register",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Untyped handler with type assertion — use RegisterTyped",
			AutoFix:     false,
		},
		{
			ID:          "A005",
			Name:        "custom-projection-runner",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Manual bus.SubscribeAll without projectionhost",
			AutoFix:     false,
		},
		{
			ID:          "A006",
			Name:        "adapter-layer-wrapping",
			Category:    "api",
			Severity:    "info",
			Confidence:  "low",
			Description: "WrapEvent/UnwrapEvent adapter methods",
			AutoFix:     false,
		},
		{
			ID:          "A007",
			Name:        "dual-model-oo-functional",
			Category:    "api",
			Severity:    "error",
			Confidence:  "medium",
			Description: "Both OO aggregates and functional deciders",
			AutoFix:     false,
		},
		{
			ID:          "A008",
			Name:        "parallel-type-system",
			Category:    "api",
			Severity:    "error",
			Confidence:  "high",
			Description: "Custom StreamID/Version types duplicating go-cqrs-lite",
			AutoFix:     false,
		},
		{
			ID:          "A009",
			Name:        "missing-stack-preset",
			Category:    "api",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Project does not use a stack/ preset",
			AutoFix:     false,
		},
		{
			ID:          "A010",
			Name:        "custom-error-types",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "low",
			Description: "Custom error interface duplicating go-error-family",
			AutoFix:     false,
		},
		{
			ID:          "A011",
			Name:        "inconsistent-json-key-casing-event-payloads",
			Category:    "api",
			Severity:    "info",
			Confidence:  "low",
			Description: "Event payload structs with mixed JSON key casing",
			AutoFix:     false,
		},
		{
			ID:          "A012",
			Name:        "missing-tombstone-handling",
			Category:    "api",
			Severity:    "info",
			Confidence:  "low",
			Description: "Fold function does not check for tombstone events",
			AutoFix:     false,
		},
		{
			ID:          "A013",
			Name:        "pointer-vs-value-basic-command",
			Category:    "api",
			Severity:    "info",
			Confidence:  "high",
			Description: "Command embeds *BasicCommand (pointer) instead of value",
			AutoFix:     false,
		},
		{
			ID:          "A014",
			Name:        "deprecated-api-usage",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Calls to deprecated APIs (event.NewEvent, dispatcher.Register)",
			AutoFix:     false,
		},
		{
			ID:          "A015",
			Name:        "global-mutable-state",
			Category:    "api",
			Severity:    "error",
			Confidence:  "medium",
			Description: "Global mutable variable — race condition risk",
			AutoFix:     false,
		},
		{
			ID:          "A016",
			Name:        "missing-idempotency-middleware",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "low",
			Description: "Command dispatcher lacks idempotency middleware",
			AutoFix:     false,
		},
		{
			ID:          "A017",
			Name:        "missing-snapshot-strategy",
			Category:    "api",
			Severity:    "info",
			Confidence:  "low",
			Description: "Repository without snapshot strategy — slow for large aggregates",
			AutoFix:     false,
		},
		{
			ID:          "A018",
			Name:        "no-actual-event-sourcing",
			Category:    "api",
			Severity:    "info",
			Confidence:  "high",
			Description: "Imports go-cqrs-lite but never calls Save/Publish",
			AutoFix:     false,
		},
		{
			ID:          "A019",
			Name:        "vendored-cqrs",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Vendored copy of go-cqrs-lite detected",
			AutoFix:     false,
		},
	}
}
