package rules

// extraRules returns metadata for boilerplate, consistency, architecture, and security rules.
func extraRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "B001",
			Name:        "single-event-helper",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Single-event helper function — use event.Single()",
			AutoFix:     false,
		},
		{
			ID:          "B002",
			Name:        "manual-repository-wiring",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Manual store+bus+repository wiring — use stack preset",
			AutoFix:     false,
		},
		{
			ID:          "B003",
			Name:        "subscribeall-large-switch",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "medium",
			Description: "SubscribeAll with >5 switch cases — split into projections",
			AutoFix:     false,
		},
		{
			ID:          "D001",
			Name:        "inconsistent-event-naming",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Mixed dot notation and PascalCase event types",
			AutoFix:     false,
		},
		{
			ID:          "D002",
			Name:        "inconsistent-json-casing",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "low",
			Description: "Mixed camelCase and snake_case JSON tags",
			AutoFix:     false,
		},
		{
			ID:          "E004",
			Name:        "event-not-in-catalog",
			Category:    "architecture",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Event type emitted but not in catalog",
			AutoFix:     false,
		},
		{
			ID:          "E005",
			Name:        "command-without-handler",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Command type defined but never registered",
			AutoFix:     false,
		},
		{
			ID:          "S001",
			Name:        "hardcoded-secrets",
			Category:    "security",
			Severity:    "critical",
			Confidence:  "medium",
			Description: "Potential hardcoded secret in string literal",
			AutoFix:     false,
		},
		{
			ID:          "C004",
			Name:        "checkpoint-before-async-complete",
			Category:    "correctness",
			Severity:    "error",
			Confidence:  "medium",
			Description: "Projection launches async work — checkpoint may save before completion",
			AutoFix:     false,
		},
		{
			ID:          "C011",
			Name:        "nondeterministic-decider",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "low",
			Description: "rand.* call inside decider — non-deterministic replay",
			AutoFix:     false,
		},
		{
			ID:          "A009",
			Name:        "missing-stack-preset",
			Category:    "api",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Project does not use a stack/ preset",
			AutoFix:     false,
		},
		{
			ID:          "A010",
			Name:        "custom-error-types",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "low",
			Description: "Custom error interface duplicating go-error-family",
			AutoFix:     false,
		},
		{
			ID:          "A012",
			Name:        "missing-tombstone-handling",
			Category:    "api",
			Severity:    "info",
			Confidence:  "low",
			Description: "Fold function does not check for tombstone events",
			AutoFix:     false,
		},
		{
			ID:          "A013",
			Name:        "pointer-vs-value-basic-command",
			Category:    "api",
			Severity:    "info",
			Confidence:  "high",
			Description: "Command embeds *BasicCommand (pointer) instead of value",
			AutoFix:     false,
		},
		{
			ID:          "A015",
			Name:        "global-mutable-state",
			Category:    "api",
			Severity:    "error",
			Confidence:  "medium",
			Description: "Global mutable variable — race condition risk",
			AutoFix:     false,
		},
		{
			ID:          "A016",
			Name:        "missing-idempotency-middleware",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "low",
			Description: "Command dispatcher lacks idempotency middleware",
			AutoFix:     false,
		},
		{
			ID:          "A018",
			Name:        "no-actual-event-sourcing",
			Category:    "api",
			Severity:    "info",
			Confidence:  "high",
			Description: "Imports go-cqrs-lite but never calls Save/Publish",
			AutoFix:     false,
		},
		{
			ID:          "A019",
			Name:        "vendored-cqrs",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Vendored copy of go-cqrs-lite detected",
			AutoFix:     false,
		},
		{
			ID:          "B004",
			Name:        "command-constructor-boilerplate",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Command with many fields — use cqrs-gen",
			AutoFix:     false,
		},
		{
			ID:          "B005",
			Name:        "fold-switch-boilerplate",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "Fold uses switch — consider decider.StrictApply",
			AutoFix:     false,
		},
		{
			ID:          "B008",
			Name:        "manual-retry-implementation",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Manual retry loop — use retry.Do",
			AutoFix:     false,
		},
		{
			ID:          "B011",
			Name:        "must-marshal-helper",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "high",
			Description: "mustMarshal helper — use event.New",
			AutoFix:     false,
		},
		{
			ID:          "B013",
			Name:        "missing-correlation-enricher",
			Category:    "boilerplate",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Repository without correlation enricher",
			AutoFix:     false,
		},
		{
			ID:          "B014",
			Name:        "missing-otel-middleware",
			Category:    "boilerplate",
			Severity:    "info",
			Confidence:  "low",
			Description: "Bus/dispatcher lacks OTel tracing middleware",
			AutoFix:     false,
		},
		{
			ID:          "D003",
			Name:        "inconsistent-logging-library",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "high",
			Description: "Project mixes multiple logging libraries",
			AutoFix:     false,
		},
		{
			ID:          "D004",
			Name:        "inconsistent-json-key-casing",
			Category:    "consistency",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Mixed camelCase and snake_case JSON tags",
			AutoFix:     false,
		},
		{
			ID:          "D005",
			Name:        "stale-documentation-version",
			Category:    "consistency",
			Severity:    "warning",
			Confidence:  "low",
			Description: "Documentation references different version than go.mod",
			AutoFix:     false,
		},
		{
			ID:          "E001",
			Name:        "layer-violation",
			Category:    "architecture",
			Severity:    "error",
			Confidence:  "high",
			Description: "Tier-0 module imports Tier-3+ module",
			AutoFix:     false,
		},
		{
			ID:          "E002",
			Name:        "circular-dependency",
			Category:    "architecture",
			Severity:    "error",
			Confidence:  "high",
			Description: "Two modules import each other",
			AutoFix:     false,
		},
		{
			ID:          "E003",
			Name:        "missing-module-boundary",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "low",
			Description: "All CQRS code in one package without boundaries",
			AutoFix:     false,
		},
		{
			ID:          "E006",
			Name:        "event-without-projection",
			Category:    "architecture",
			Severity:    "info",
			Confidence:  "low",
			Description: "Event type emitted but no projection handles it",
			AutoFix:     false,
		},
		{
			ID:          "E007",
			Name:        "query-without-handler",
			Category:    "architecture",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Query type defined but never registered",
			AutoFix:     false,
		},
		{
			ID:          "S002",
			Name:        "missing-encryption-for-sensitive-payloads",
			Category:    "security",
			Severity:    "error",
			Confidence:  "medium",
			Description: "PII event payloads without encryption middleware",
			AutoFix:     false,
		},
		{
			ID:          "S003",
			Name:        "missing-event-signing",
			Category:    "security",
			Severity:    "warning",
			Confidence:  "low",
			Description: "Event store without signing middleware",
			AutoFix:     false,
		},
	}
}
