// Package rules provides centralized rule registration for cqrs-lint.
package rules

import (
	"slices"
	"sync"
)

type RuleInfo struct {
	ID          string
	Name        string
	Category    string
	Severity    string
	Confidence  string
	Description string
	AutoFix     bool
	// DocURL is an optional link to detailed documentation for this rule.
	// When set, findings include it in Metadata for SARIF/JSON output.
	DocURL string
}

// allRulesCache memoizes the full rule catalog so AllRules is only built once.
// Called from detectorCategory, renderRulesTable, ListRules, and the meta-test.
//
//nolint:gochecknoglobals // intentional memoized cache
var allRulesCache = sync.OnceValue(func() []RuleInfo {
	return slices.Concat(
		correctnessRules(),
		apiRules(),
		boilerplateRules(),
		consistencyRules(),
		architectureRules(),
		securityRules(),
		performanceRules(),
		versionRules(),
		testingRules(),
		adoptionRules(),
	)
})

// AllRules returns metadata for all available rules, organized by category.
// The result is cached after the first call.
func AllRules() []RuleInfo {
	return allRulesCache()
}

// ruleLookupCache memoizes a rule-ID → RuleInfo map for LookupRule.
//
//nolint:gochecknoglobals // intentional memoized cache
var ruleLookupCache = sync.OnceValue(func() map[string]RuleInfo {
	m := make(map[string]RuleInfo, 180)

	for _, r := range allRulesCache() {
		m[r.ID] = r
	}

	return m
})

// LookupRule returns the catalog entry for the given rule ID (e.g., "C001").
// The boolean is false if the rule is not in the catalog.
func LookupRule(id string) (RuleInfo, bool) {
	r, ok := ruleLookupCache()[id]
	return r, ok
}

func correctnessRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "C001",
			Name:        "missing-tx-commit",
			Category:    "correctness",
			Severity:    "critical",
			Confidence:  "high",
			Description: "Transaction wrapper returns nil instead of tx.Commit()",
			AutoFix:     true,
			DocURL:      "https://github.com/LarsArtmann/go-cqrs-lite/blob/main/cmd/cqrs-lint/RULES.md#c001",
		},
		{
			ID:          "C002",
			Name:        "broken-command-id",
			Category:    "correctness",
			Severity:    "critical",
			Confidence:  "high",
			Description: "Command ID() returns zero value — breaks idempotency",
			AutoFix:     false,
		},
		{
			ID:          "C003",
			Name:        "silent-unknown-event-fold",
			Category:    "correctness",
			Severity:    "error",
			Confidence:  "high",
			Description: "Fold function silently ignores unknown event types",
			AutoFix:     true,
		},
		{
			ID:          "C004",
			Name:        "checkpoint-before-async-complete",
			Category:    "correctness",
			Severity:    "error",
			Confidence:  "medium",
			Description: "Projection launches async work — checkpoint may save before completion",
			AutoFix:     false,
		},
		{
			ID:          "C005",
			Name:        "raw-json-unmarshal-payload",
			Category:    "correctness",
			Severity:    "error",
			Confidence:  "high",
			Description: "Raw json.Unmarshal on event payload instead of DecodePayloadAuto",
			AutoFix:     false,
		},
		{
			ID:          "C006",
			Name:        "manual-version-arithmetic",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Manual event.Version(x.Int()+1) instead of x.Increment()",
			AutoFix:     true,
		},
		{
			ID:          "C007",
			Name:        "time-now-in-decider",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "time.Now() inside decider — non-deterministic",
			AutoFix:     false,
		},
		{
			ID:          "C008",
			Name:        "float64-for-money",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "float64 field with monetary name — use decimal or cents",
			AutoFix:     false,
			DocURL:      "https://github.com/LarsArtmann/go-cqrs-lite/blob/main/cmd/cqrs-lint/RULES.md#c008",
		},
		{
			ID:          "C009",
			Name:        "panic-in-production",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "panic() in production code — use error returns",
			AutoFix:     false,
		},
		{
			ID:          "C010",
			Name:        "swallowed-error-in-fold",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Error from decode/unmarshal discarded in fold",
			AutoFix:     false,
			DocURL:      "https://github.com/LarsArtmann/go-cqrs-lite/blob/main/cmd/cqrs-lint/RULES.md#c010",
		},
		{
			ID:          "C011",
			Name:        "nondeterministic-decider",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "low",
			Description: "rand.* call inside decider — non-deterministic replay",
			AutoFix:     false,
		},
		{
			ID:          "C012",
			Name:        "missing-error-return-in-with-tx",
			Category:    "correctness",
			Severity:    "critical",
			Confidence:  "high",
			Description: "withTx ignores body error — failures silently lost",
			AutoFix:     false,
		},
		{
			ID:          "C013",
			Name:        "time-time-in-event-payload",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "time.Time field in event payload loses timezone via CBOR epoch encoding",
			AutoFix:     false,
			DocURL:      "https://github.com/LarsArtmann/go-cqrs-lite/blob/main/docs/TIMEZONE_HANDLING.md",
		},
		{
			ID:          "C014",
			Name:        "time-local-usage",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "time.Local causes silent data corruption across timezone boundaries",
			AutoFix:     false,
		},
		{
			ID:          "C015",
			Name:        "unchecked-close",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Close() error discarded — resource leak or silent data loss risk",
			AutoFix:     false,
		},
		{
			ID:          "C016",
			Name:        "background-in-handler",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "context.Background()/TODO() in a handler with a ctx param — discards cancellation, timeouts, tracing",
			AutoFix:     false,
		},
		{
			ID:          "C017",
			Name:        "inmem-store-persistent-eventstore",
			Category:    "correctness",
			Severity:    "error",
			Confidence:  "high",
			Description: "In-memory snapshot/checkpoint/dead-letter/timer store with persistent event store — lost on restart",
			AutoFix:     false,
			DocURL:      "https://github.com/LarsArtmann/go-cqrs-lite/blob/main/cmd/cqrs-lint/RULES.md#c017",
		},
		{
			ID:          "C018",
			Name:        "silent-journal-fallback",
			Category:    "correctness",
			Severity:    "error",
			Confidence:  "high",
			Description: "memory.NewMemoryStore() used as journal fallback — projections replay from empty journal",
			AutoFix:     false,
		},
		{
			ID:          "C019",
			Name:        "multiple-repos-same-aggregate",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Multiple Repository instances for the same aggregate type — wastes singleflight/cache",
			AutoFix:     false,
		},
		{
			ID:          "C020",
			Name:        "panic-in-handler",
			Category:    "correctness",
			Severity:    "error",
			Confidence:  "high",
			Description: "panic() in bus.Subscribe/SubscribeAll handler — crashes the bus/projection host",
			AutoFix:     false,
		},
		{
			ID:          "C021",
			Name:        "mutex-held-during-decode",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Payload decode while mutex is held — serializes all event processing",
			AutoFix:     false,
		},
		{
			ID:          "C022",
			Name:        "context-discarded",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "_ = ctx explicitly discards context — breaks cancellation, timeouts, tracing",
			AutoFix:     false,
		},
		{
			ID:          "C023",
			Name:        "shutdown-error-ignored",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Stop/Close/Shutdown error ignored — pending events or resources may be lost",
			AutoFix:     false,
		},
		{
			ID:          "C024",
			Name:        "dual-write-without-rollback",
			Category:    "correctness",
			Severity:    "error",
			Confidence:  "medium",
			Description: "In-memory mutation + DB write without transaction — state diverges on failure",
			AutoFix:     false,
		},
		{
			ID:          "C025",
			Name:        "bare-errorf-in-cqrs",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "fmt.Errorf without %w in CQRS code — loses error classification",
			AutoFix:     false,
		},
		{
			ID:          "C026",
			Name:        "idempotency-ttl-mismatch",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Literal TTL passed but a TTL constant is defined and not used — dead/misleading code",
			AutoFix:     false,
		},
		{
			ID:          "C027",
			Name:        "bus-subscription-alongside-projectionhost",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "bus.Subscribe alongside projectionhost — events may be processed twice",
			AutoFix:     false,
		},
		{
			ID:          "C028",
			Name:        "swallowed-cqrs-error",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Error from Dispatch/Execute/Load/Register discarded — CQRS operation failures indicate real problems",
			AutoFix:     false,
		},
		{
			ID:          "C029",
			Name:        "queryidempotency-nil-keyextractor",
			Category:    "correctness",
			Severity:    "error",
			Confidence:  "high",
			Description: "QueryIdempotency with nil keyExtractor panics at runtime — queries have no default identity",
			AutoFix:     false,
		},
		{
			ID:          "C030",
			Name:        "no-ctx-cancel-in-loop",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Infinite loop without context cancellation — goroutine leaks on shutdown",
			AutoFix:     false,
		},
		{
			ID:          "C031",
			Name:        "error-swallow-in-handler",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Handler checks error but returns nil — command/query appears successful when it failed",
			AutoFix:     false,
		},
		{
			ID:          "C032",
			Name:        "ctx-propagation-gap",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "context.Background()/TODO() inside handler that receives ctx — breaks tracing and cancellation",
			AutoFix:     false,
		},
		{
			ID:          "C033",
			Name:        "missing-error-wrapping",
			Category:    "correctness",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Bare return err from CQRS call — wrap with context for debuggability",
			AutoFix:     false,
		},
		{
			ID:          "C034",
			Name:        "goroutine-without-ctx",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "go func() without ctx — goroutine outlives parent handler, resource leak on shutdown",
			AutoFix:     false,
		},
		{
			ID:          "C035",
			Name:        "unprotected-map-field",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Map field without sync.Mutex/sync.RWMutex in read model/handler — data race risk in concurrent handlers",
			AutoFix:     false,
		},
		{
			ID:          "C036",
			Name:        "store-backend-mismatch",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Checkpoint/snapshot/idempotency store backend differs from event store — crash-recovery guarantees break",
			AutoFix:     false,
		},
		{
			ID:          "C037",
			Name:        "snapshot-codec-mismatch",
			Category:    "correctness",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Snapshot store codec differs from repository codec — snapshot cannot be decoded, loads as corrupt/zero state",
			AutoFix:     false,
		},
	}
}

func apiRules() []RuleInfo {
	return []RuleInfo{
		{
			ID:          "A001",
			Name:        "manual-command-interface",
			Category:    "api",
			Severity:    "error",
			Confidence:  "high",
			Description: "Manual Type()/ID()/StreamID() instead of BasicCommand embedding",
			AutoFix:     false,
		},
		{
			ID:          "A002",
			Name:        "newevent-manual-marshal",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "high",
			Description: "event.NewEvent with json.Marshal — use event.New for auto-marshal",
			AutoFix:     false,
		},
		{
			ID:          "A003",
			Name:        "explicit-codec-in-decode",
			Category:    "api",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Explicit codec in DecodePayload — use DecodePayloadAuto",
			AutoFix:     false,
		},
		{
			ID:          "A004",
			Name:        "untyped-dispatch-register",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Untyped handler with type assertion — use RegisterTyped",
			AutoFix:     false,
		},
		{
			ID:          "A005",
			Name:        "custom-projection-runner",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Manual bus.SubscribeAll without projectionhost",
			AutoFix:     false,
		},
		{
			ID:          "A006",
			Name:        "adapter-layer-wrapping",
			Category:    "api",
			Severity:    "info",
			Confidence:  "low",
			Description: "WrapEvent/UnwrapEvent adapter methods",
			AutoFix:     false,
		},
		{
			ID:          "A007",
			Name:        "dual-model-oo-functional",
			Category:    "api",
			Severity:    "error",
			Confidence:  "medium",
			Description: "Both OO aggregates and functional deciders",
			AutoFix:     false,
		},
		{
			ID:          "A008",
			Name:        "parallel-type-system",
			Category:    "api",
			Severity:    "error",
			Confidence:  "high",
			Description: "Custom StreamID/Version types duplicating go-cqrs-lite",
			AutoFix:     false,
		},
		{
			ID:          "A009",
			Name:        "missing-stack-preset",
			Category:    "api",
			Severity:    "info",
			Confidence:  "medium",
			Description: "Project does not use a stack/ preset",
			AutoFix:     false,
		},
		{
			ID:          "A010",
			Name:        "custom-error-types",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "low",
			Description: "Custom error interface duplicating go-error-family",
			AutoFix:     false,
		},
		{
			ID:          "A011",
			Name:        "inconsistent-json-key-casing-event-payloads",
			Category:    "api",
			Severity:    "info",
			Confidence:  "low",
			Description: "Event payload structs with mixed JSON key casing",
			AutoFix:     false,
		},
		{
			ID:          "A012",
			Name:        "missing-tombstone-handling",
			Category:    "api",
			Severity:    "info",
			Confidence:  "low",
			Description: "Fold function does not check for tombstone events",
			AutoFix:     false,
		},
		{
			ID:          "A013",
			Name:        "pointer-vs-value-basic-command",
			Category:    "api",
			Severity:    "info",
			Confidence:  "high",
			Description: "Command embeds *BasicCommand (pointer) instead of value",
			AutoFix:     false,
		},
		{
			ID:          "A014",
			Name:        "deprecated-api-usage",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Calls to deprecated APIs (event.NewEvent, dispatcher.Register)",
			AutoFix:     false,
		},
		{
			ID:          "A015",
			Name:        "global-mutable-state",
			Category:    "api",
			Severity:    "error",
			Confidence:  "medium",
			Description: "Global mutable variable — race condition risk",
			AutoFix:     false,
		},
		{
			ID:          "A016",
			Name:        "missing-idempotency-middleware",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "low",
			Description: "Command dispatcher lacks idempotency middleware",
			AutoFix:     false,
		},
		{
			ID:          "A017",
			Name:        "missing-snapshot-strategy",
			Category:    "api",
			Severity:    "info",
			Confidence:  "low",
			Description: "Repository without snapshot strategy — slow for large aggregates",
			AutoFix:     false,
		},
		{
			ID:          "A018",
			Name:        "no-actual-event-sourcing",
			Category:    "api",
			Severity:    "info",
			Confidence:  "high",
			Description: "Imports go-cqrs-lite but never calls Save/Publish",
			AutoFix:     false,
		},
		{
			ID:          "A019",
			Name:        "vendored-cqrs",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Vendored copy of go-cqrs-lite detected",
			AutoFix:     false,
		},
		{
			ID:          "A020",
			Name:        "custom-event-bus",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Custom event.Bus implementation — use watermill.NewEventBus() or the library's memory bus",
			AutoFix:     false,
		},
		{
			ID:          "A021",
			Name:        "custom-event-store",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Custom event.Store implementation — use storage/memory or a SQL/Pebble backend",
			AutoFix:     false,
		},
		{
			ID:          "A022",
			Name:        "raw-otel-tracer",
			Category:    "api",
			Severity:    "info",
			Confidence:  "high",
			Description: "Raw otel.Tracer/Meter instead of cqrsotel.NewTracer/NewMeter",
			AutoFix:     false,
		},
		{
			ID:          "A023",
			Name:        "custom-snapshot-store",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "medium",
			Description: "Custom snapshot store — use storage/memory.NewMemorySnapshotStore()",
			AutoFix:     false,
		},
		{
			ID:          "A024",
			Name:        "decorative-event-sourcing",
			Category:    "api",
			Severity:    "info",
			Confidence:  "high",
			Description: "Imports event/ and decider/ but never creates events or wires a repository",
			AutoFix:     false,
		},
		{
			ID:          "A025",
			Name:        "command-query-no-events",
			Category:    "api",
			Severity:    "info",
			Confidence:  "low",
			Description: "Command/query dispatchers without event sourcing — may miss audit trail and replay",
			AutoFix:     false,
		},
		{
			ID:          "A026",
			Name:        "event-bus-only",
			Category:    "api",
			Severity:    "info",
			Confidence:  "low",
			Description: "Event/ and watermill only — no command, decider, or query (bare event bus)",
			AutoFix:     false,
		},
		{
			ID:          "A027",
			Name:        "repeated-withcodec",
			Category:    "api",
			Severity:    "info",
			Confidence:  "high",
			Description: "event.WithCodec called 3+ times in one file — set codec once via event.DefaultCodec",
			AutoFix:     false,
		},
		{
			ID:          "A029",
			Name:        "usepublish-stub",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "high",
			Description: "UsePublish method is a stub returning nil — publish middleware chain discarded",
			AutoFix:     false,
		},
		{
			ID:          "A030",
			Name:        "incomplete-snapshot-config",
			Category:    "api",
			Severity:    "error",
			Confidence:  "high",
			Description: "WithSnapshotStrategy without WithSnapshotStore — ErrIncompleteSnapshotConfig at runtime",
			AutoFix:     false,
		},
		{
			ID:          "A032",
			Name:        "string-id-instead-of-branded",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "high",
			Description: "Struct field named *ID with type string/int — use id.Of[T] branded ID for type safety",
			AutoFix:     false,
		},
		{
			ID:          "A033",
			Name:        "branded-id-string-roundtrip",
			Category:    "api",
			Severity:    "warning",
			Confidence:  "high",
			Description: "id.Parse[T](x.String()) — pointless branded-ID roundtrip that discards the typed value and re-runs validation",
			AutoFix:     false,
		},
	}
}
