// Command go-cqrs-lite-catalog generates documentation files (OpenAPI, AsyncAPI,
// D2, llms.txt) from a catalog definition.
//
// Usage:
//
//	go-cqrs-lite-catalog [format] [output-dir]
//
// Formats: openapi, asyncapi, d2, llms (default: openapi)
//
// This CLI generates from a built-in demo catalog. For real projects, import
// the catalog library directly and call the exporters programmatically.
package main

import (
	"encoding/json/v2"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/larsartmann/go-cqrs-lite/catalog/v4"
	"github.com/larsartmann/go-cqrs-lite/catalog/v4/asyncapi"
	"github.com/larsartmann/go-cqrs-lite/catalog/v4/d2"
	"github.com/larsartmann/go-cqrs-lite/catalog/v4/openapi"
)

func main() {
	format := flag.String("format", "openapi", "output format: openapi, asyncapi, d2, llms")
	title := flag.String("title", "Demo API", "document title")
	version := flag.String("version", "1.0.0", "document version")
	output := flag.String("o", ".", "output directory")

	flag.Parse()

	cat := buildDemoCatalog(*title, *version)

	if err := generate(cat, *format, *output, *title, *version); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s documentation in %s\n", *format, *output)
}

func buildDemoCatalog(title, version string) *catalog.Catalog {
	reg := catalog.NewRegistry(title, version)
	reg.AddService(catalog.Service{
		ID:      "demo-svc",
		Name:    "Demo Service",
		Version: catalog.Version(version),
		Summary: "A demo service showing REST catalog features",
		Commands: []catalog.Message{
			{
				ID:      "item.create",
				Name:    "CreateItem",
				Version: "1.0.0",
				Kind:    catalog.CommandMessage,
				Operation: &catalog.Operation{
					Method:      "POST",
					Path:        "/api/items",
					StatusCodes: []string{"201", "400"},
				},
				Responses: []catalog.ResponseSpec{
					{StatusCode: "201", Description: "Item created"},
				},
			},
		},
		Queries: []catalog.Message{
			{
				ID:      "item.list",
				Name:    "ListItems",
				Version: "1.0.0",
				Kind:    catalog.QueryMessage,
				Operation: &catalog.Operation{
					Method: "GET",
					Path:   "/api/items",
				},
			},
		},
	})

	return reg.Build()
}

func generate(cat *catalog.Catalog, format, dir, title, version string) error {
	switch format {
	case "openapi":
		doc := openapi.NewExporter(title, version).Export(cat)

		return writeJSON(filepath.Join(dir, "openapi.json"), doc)
	case "asyncapi":
		doc := asyncapi.NewExporter(title, version).Export(cat)

		return writeJSON(filepath.Join(dir, "asyncapi.json"), doc)
	case "d2":
		output := d2.NewExporter(title, version).Export(cat)

		return os.WriteFile(filepath.Join(dir, "diagram.d2"), []byte(output), 0o644)
	case "llms":
		// llms.txt is generated by the eventcatalog exporter
		// For CLI simplicity, we generate a basic summary
		return writeLLMsTxt(filepath.Join(dir, "llms.txt"), cat)
	default:
		return fmt.Errorf("unknown format: %s", format)
	}
}

func writeJSON(path string, v any) error {
	data, err := json.Marshal(v, json.Deterministic(true))
	if err != nil {
		return err
	}

	return os.WriteFile(path, data, 0o644)
}

func writeLLMsTxt(path string, cat *catalog.Catalog) error {
	content := fmt.Sprintf("# %s\n\n> Auto-generated catalog summary.\n\n", cat.Title)

	var (
		contentSb116 strings.Builder
		contentSb122 strings.Builder
	)

	for _, svc := range cat.Services {
		fmt.Fprintf(&contentSb116, "## %s (%s)\n\n", svc.Name, svc.ID)

		var contentSb119 strings.Builder
		for _, cmd := range svc.Commands {
			fmt.Fprintf(&contentSb119, "- Command: %s", cmd.Name)

			if cmd.Operation != nil {
				fmt.Fprintf(&contentSb119, " [%s %s]", cmd.Operation.Method, cmd.Operation.Path)
			}

			contentSb119.WriteString("\n")
		}

		contentSb122.WriteString(contentSb119.String())

		var contentSb127 strings.Builder
		for _, q := range svc.Queries {
			fmt.Fprintf(&contentSb127, "- Query: %s", q.Name)

			if q.Operation != nil {
				fmt.Fprintf(&contentSb127, " [%s %s]", q.Operation.Method, q.Operation.Path)
			}

			contentSb127.WriteString("\n")
		}

		contentSb122.WriteString(contentSb127.String())
	}

	content += contentSb122.String()

	content += contentSb116.String()

	return os.WriteFile(path, []byte(content), 0o644)
}
