// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: cqrs.proto

package cqrsproto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommandEnvelope wraps a CQRS command for wire transmission.
// The payload is JSON-encoded (matching the watermill protocol).
type CommandEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                                                                   // command type (e.g. "user.create")
	AggregateId   string                 `protobuf:"bytes,2,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`                                                  // aggregate ID (ULID)
	AggregateType string                 `protobuf:"bytes,3,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`                                            // aggregate type (e.g. "User")
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                                                                             // JSON-encoded command payload
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // command metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandEnvelope) Reset() {
	*x = CommandEnvelope{}
	mi := &file_cqrs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandEnvelope) ProtoMessage() {}

func (x *CommandEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_cqrs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandEnvelope.ProtoReflect.Descriptor instead.
func (*CommandEnvelope) Descriptor() ([]byte, []int) {
	return file_cqrs_proto_rawDescGZIP(), []int{0}
}

func (x *CommandEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CommandEnvelope) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *CommandEnvelope) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *CommandEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CommandEnvelope) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CommandResult is the response from a command dispatch.
type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_cqrs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_cqrs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_cqrs_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// QueryEnvelope wraps a CQRS query for wire transmission.
type QueryEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                                                                   // query type (e.g. "user.get")
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                                                                             // JSON-encoded query payload
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // query metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEnvelope) Reset() {
	*x = QueryEnvelope{}
	mi := &file_cqrs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEnvelope) ProtoMessage() {}

func (x *QueryEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_cqrs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEnvelope.ProtoReflect.Descriptor instead.
func (*QueryEnvelope) Descriptor() ([]byte, []int) {
	return file_cqrs_proto_rawDescGZIP(), []int{2}
}

func (x *QueryEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *QueryEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *QueryEnvelope) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// QueryResult is the response from a query dispatch.
type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded result
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_cqrs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_cqrs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_cqrs_proto_rawDescGZIP(), []int{3}
}

func (x *QueryResult) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *QueryResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_cqrs_proto protoreflect.FileDescriptor

const file_cqrs_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"cqrs.proto\x12\acqrs.v1\"\x8a\x02\n" +
	"\x0fCommandEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12!\n" +
	"\faggregate_id\x18\x02 \x01(\tR\vaggregateId\x12%\n" +
	"\x0eaggregate_type\x18\x03 \x01(\tR\raggregateType\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12B\n" +
	"\bmetadata\x18\x05 \x03(\v2&.cqrs.v1.CommandEnvelope.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\rCommandResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xbc\x01\n" +
	"\rQueryEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12@\n" +
	"\bmetadata\x18\x03 \x03(\v2$.cqrs.v1.QueryEnvelope.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\vQueryResult\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2N\n" +
	"\x0eCommandService\x12<\n" +
	"\bDispatch\x12\x18.cqrs.v1.CommandEnvelope\x1a\x16.cqrs.v1.CommandResult2C\n" +
	"\fQueryService\x123\n" +
	"\x03Ask\x12\x16.cqrs.v1.QueryEnvelope\x1a\x14.cqrs.v1.QueryResultBGZEgithub.com/larsartmann/go-cqrs-lite/transport/grpc/v3/proto;cqrsprotob\x06proto3"

var (
	file_cqrs_proto_rawDescOnce sync.Once
	file_cqrs_proto_rawDescData []byte
)

func file_cqrs_proto_rawDescGZIP() []byte {
	file_cqrs_proto_rawDescOnce.Do(func() {
		file_cqrs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cqrs_proto_rawDesc), len(file_cqrs_proto_rawDesc)))
	})
	return file_cqrs_proto_rawDescData
}

var (
	file_cqrs_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
	file_cqrs_proto_goTypes  = []any{
		(*CommandEnvelope)(nil), // 0: cqrs.v1.CommandEnvelope
		(*CommandResult)(nil),   // 1: cqrs.v1.CommandResult
		(*QueryEnvelope)(nil),   // 2: cqrs.v1.QueryEnvelope
		(*QueryResult)(nil),     // 3: cqrs.v1.QueryResult
		nil,                     // 4: cqrs.v1.CommandEnvelope.MetadataEntry
		nil,                     // 5: cqrs.v1.QueryEnvelope.MetadataEntry
	}
)
var file_cqrs_proto_depIdxs = []int32{
	4, // 0: cqrs.v1.CommandEnvelope.metadata:type_name -> cqrs.v1.CommandEnvelope.MetadataEntry
	5, // 1: cqrs.v1.QueryEnvelope.metadata:type_name -> cqrs.v1.QueryEnvelope.MetadataEntry
	0, // 2: cqrs.v1.CommandService.Dispatch:input_type -> cqrs.v1.CommandEnvelope
	2, // 3: cqrs.v1.QueryService.Ask:input_type -> cqrs.v1.QueryEnvelope
	1, // 4: cqrs.v1.CommandService.Dispatch:output_type -> cqrs.v1.CommandResult
	3, // 5: cqrs.v1.QueryService.Ask:output_type -> cqrs.v1.QueryResult
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cqrs_proto_init() }
func file_cqrs_proto_init() {
	if File_cqrs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cqrs_proto_rawDesc), len(file_cqrs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_cqrs_proto_goTypes,
		DependencyIndexes: file_cqrs_proto_depIdxs,
		MessageInfos:      file_cqrs_proto_msgTypes,
	}.Build()
	File_cqrs_proto = out.File
	file_cqrs_proto_goTypes = nil
	file_cqrs_proto_depIdxs = nil
}
