package main

import (
	"fmt"
	"strings"
)

type genSpec struct {
	imports    string
	writeEntry func(b *strings.Builder, e Entry)
}

//nolint:gochecknoglobals // static code-generation dispatch table; data, not state
var genSpecs = map[string]genSpec{
	genTypeCommand: {
		imports:    commandImports,
		writeEntry: writeCommandHandler,
	},
	genTypeQuery: {
		imports:    queryImports,
		writeEntry: writeQueryHandler,
	},
	genTypeEvent: {
		imports:    eventImports,
		writeEntry: writeEventHandler,
	},
}

func writeCommandHandler(b *strings.Builder, e Entry) {
	fmt.Fprintf(
		b,
		"// Register%sHandler registers a typed handler for %s commands.\n",
		e.StructName,
		e.CommandType,
	)
	fmt.Fprintf(
		b,
		"func Register%sHandler(d *command.Dispatcher, handler func(context.Context, *%s) error) error {\n",
		e.StructName,
		e.StructName,
	)
	fmt.Fprintf(b, "\treturn command.RegisterTyped(d, %q, handler)\n", e.CommandType)
	b.WriteString("}\n\n")
}

func writeQueryHandler(b *strings.Builder, e Entry) {
	fmt.Fprintf(
		b,
		"// Register%sHandler registers a typed handler for %s queries.\n",
		e.StructName,
		e.CommandType,
	)
	fmt.Fprintf(
		b,
		"func Register%sHandler[R any](d *query.Dispatcher, handler func(context.Context, *%s) (R, error)) error {\n",
		e.StructName,
		e.StructName,
	)
	fmt.Fprintf(
		b,
		"\treturn query.RegisterTyped[*%s, R](d, %q, handler)\n",
		e.StructName,
		e.CommandType,
	)
	b.WriteString("}\n\n")
}

func generate(pkg, genType string, entries []Entry) string {
	spec := genSpecs[genType]

	var b strings.Builder

	b.WriteString("// Code generated by cqrs-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString(spec.imports)

	for _, e := range entries {
		spec.writeEntry(&b, e)
	}

	return b.String()
}
