package main

import (
	"fmt"
	"go/format"
	"strings"
)

type genSpec struct {
	imports    string
	writeEntry func(b *strings.Builder, e Entry)
}

//nolint:gochecknoglobals // static code-generation dispatch table; data, not state
var genSpecs = map[string]genSpec{
	genTypeCommand: {
		imports:    commandImports,
		writeEntry: writeCommandHandler,
	},
	genTypeQuery: {
		imports:    queryImports,
		writeEntry: writeQueryHandler,
	},
	genTypeEvent: {
		imports:    eventImports,
		writeEntry: writeEventHandler,
	},
}

func writeCommandHandler(b *strings.Builder, e Entry) {
	fmt.Fprintf(
		b,
		"// Register%sHandler registers a typed handler for %s commands.\n",
		e.StructName,
		e.TypeName,
	)
	fmt.Fprintf(
		b,
		"func Register%sHandler(d *command.Dispatcher, handler func(context.Context, *%s) error) error {\n",
		e.StructName,
		e.StructName,
	)
	fmt.Fprintf(b, "\treturn command.RegisterTyped(d, %q, handler)\n", e.TypeName)
	b.WriteString("}\n\n")
}

func writeQueryHandler(b *strings.Builder, e Entry) {
	fmt.Fprintf(
		b,
		"// Register%sHandler registers a typed handler for %s queries.\n",
		e.StructName,
		e.TypeName,
	)
	fmt.Fprintf(
		b,
		"func Register%sHandler[R any](d *query.Dispatcher, handler func(context.Context, *%s) (R, error)) error {\n",
		e.StructName,
		e.StructName,
	)
	fmt.Fprintf(
		b,
		"\treturn query.RegisterTyped[*%s, R](d, %q, handler)\n",
		e.StructName,
		e.TypeName,
	)
	b.WriteString("}\n\n")
}

func writeEventHandler(b *strings.Builder, e Entry) {
	fmt.Fprintf(
		b,
		"// Register%sHandler registers a typed event handler for %s events.\n",
		e.StructName,
		e.TypeName,
	)
	fmt.Fprintf(
		b,
		"func Register%sHandler(bus event.Subscriber, c codec.Codec, handler func(context.Context, %s) error) error {\n",
		e.StructName,
		e.StructName,
	)
	fmt.Fprintf(
		b,
		"\treturn bus.Subscribe(event.Type(%q), func(ctx context.Context, evt event.Event) error {\n",
		e.TypeName,
	)
	fmt.Fprintf(b, "\t\tp, err := event.DecodePayload[%s](evt, c)\n", e.StructName)
	b.WriteString("\t\tif err != nil {\n")
	b.WriteString("\t\t\treturn err\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\treturn handler(ctx, p)\n")
	b.WriteString("\t})\n")
	b.WriteString("}\n\n")
}

// generate renders the registration boilerplate and runs it through go/format
// so the emitted file is always valid, gofmt-clean Go. A parse failure here
// signals a bug in the generator itself (a template referencing a bad name),
// not a user error — hence the returned error.
func generate(pkg, handlerType string, entries []Entry) (string, error) {
	spec := genSpecs[handlerType]

	var b strings.Builder

	b.WriteString("// Code generated by cqrs-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString(spec.imports)

	for _, e := range entries {
		spec.writeEntry(&b, e)
	}

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf(
			"format generated %s handlers: %w\n--- generated source ---\n%s",
			handlerType,
			err,
			b.String(),
		)
	}

	return string(formatted), nil
}
