// cqrs-gen generates typed handler registration code from Go structs marked with
// cqrs annotations.
//
// Usage:
//
//	cqrs-gen -type=command -output=commands_gen.go ./...
//	cqrs-gen -type=query -output=queries_gen.go ./...
//
// Marker comments in source code:
//
//	//cqrs:command CreateUser
//	type CreateUserCmd struct {
//	    *command.BasicCommand
//	    Name string
//	}
package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

const (
	genTypeCommand = "command"
	genTypeQuery   = "query"
)

//nolint:gochecknoglobals // CLI flags
var (
	genType    = flag.String("type", genTypeCommand, "handler type to generate: command or query")
	outputFile = flag.String("output", "handlers_gen.go", "output file path")
	pkgName    = flag.String(
		"pkg",
		"",
		"package name for generated file (defaults to current directory)",
	)
)

func main() {
	flag.Parse()
	os.Exit(run(*genType, *outputFile, *pkgName, flag.Args()))
}

func run(genType, outputFile, pkg string, paths []string) int {
	if genType != genTypeCommand && genType != genTypeQuery {
		fmt.Fprintf(os.Stderr, "invalid type %q: must be 'command' or 'query'\n", genType)
		return 1
	}

	if len(paths) == 0 {
		paths = []string{"."}
	}

	entries, err := scan(paths, genType)
	if err != nil {
		fmt.Fprintf(os.Stderr, "scan: %v\n", err)
		return 1
	}

	if len(entries) == 0 {
		fmt.Fprintln(os.Stderr, "no cqrs markers found")
		return 0
	}

	if pkg == "" {
		pkg = filepath.Base(mustAbs(paths[0]))
	}

	code := generate(pkg, genType, entries)

	if err := os.WriteFile(outputFile, []byte(code), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		return 1
	}

	fmt.Printf("generated %d handlers → %s\n", len(entries), outputFile)
	return 0
}

func mustAbs(p string) string {
	abs, err := filepath.Abs(p)
	if err != nil {
		return p
	}
	return abs
}

// Entry represents a single discovered cqrs marker.
type Entry struct {
	CommandType string
	StructName  string
	PackagePath string
}

func scan(paths []string, genType string) ([]Entry, error) {
	var entries []Entry

	for _, path := range paths {
		found, err := scanPath(path, genType)
		if err != nil {
			return nil, err
		}
		entries = append(entries, found...)
	}

	return entries, nil
}

func scanPath(root, genType string) ([]Entry, error) {
	var entries []Entry

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}

		found, err := scanFile(path, genType)
		if err != nil {
			return fmt.Errorf("scan %s: %w", path, err)
		}
		entries = append(entries, found...)
		return nil
	})

	return entries, err
}

func scanFile(path, genType string) ([]Entry, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	var entries []Entry
	prefix := "//cqrs:" + genType + " "

	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			cmdType := extractMarker(genDecl.Doc, prefix)
			if cmdType == "" {
				cmdType = extractMarker(ts.Doc, prefix)
			}
			if cmdType == "" {
				continue
			}

			entries = append(entries, Entry{
				CommandType: cmdType,
				StructName:  ts.Name.Name,
				PackagePath: f.Name.Name,
			})
		}
	}

	return entries, nil
}

func extractMarker(doc *ast.CommentGroup, prefix string) string {
	if doc == nil {
		return ""
	}
	for _, c := range doc.List {
		if after, ok := strings.CutPrefix(c.Text, prefix); ok {
			return after
		}
	}
	return ""
}

func generate(pkg, genType string, entries []Entry) string {
	var b strings.Builder

	b.WriteString("// Code generated by cqrs-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	if genType == genTypeCommand {
		b.WriteString(`import (
	"context"

	"github.com/larsartmann/go-cqrs-lite/core/command"
)

`)
		for _, e := range entries {
			fmt.Fprintf(
				&b,
				"// Register%sHandler registers a typed handler for %s commands.\n",
				e.StructName,
				e.CommandType,
			)
			fmt.Fprintf(
				&b,
				"func Register%sHandler(d *command.Dispatcher, handler func(context.Context, *%s) error) error {\n",
				e.StructName,
				e.StructName,
			)
			fmt.Fprintf(&b, "\treturn command.RegisterTyped(d, %q, handler)\n", e.CommandType)
			b.WriteString("}\n\n")
		}
	} else {
		b.WriteString(`import (
	"context"

	"github.com/larsartmann/go-cqrs-lite/core/query"
)

`)
		for _, e := range entries {
			fmt.Fprintf(
				&b,
				"// Register%sHandler registers a typed handler for %s queries.\n",
				e.StructName,
				e.CommandType,
			)
			fmt.Fprintf(
				&b,
				"func Register%sHandler(d *query.Dispatcher, handler func(context.Context, *%s) error) error {\n",
				e.StructName,
				e.StructName,
			)
			fmt.Fprintf(&b, "\treturn query.RegisterTyped(d, %q, handler)\n", e.CommandType)
			b.WriteString("}\n\n")
		}
	}

	return b.String()
}
